/*
 * (C) Copyright 2016 - 2017, Xilinx, Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 */

/* ==============================================================
 * File generated by Vivado(TM) HLS - High-Level Synthesis from C,
 * C++ and SystemC
 * Version: 2016.1
 * Copyright (C) 2016,2017 Xilinx Inc. All rights reserved.
 *
 * ==============================================================

 * CTRL
 * 0x00000 : Control signals
 *           bit 0  - ap_start (Read/Write/COH)
 *           bit 1  - ap_done (Read/COR)
 *           bit 2  - ap_idle (Read)
 *           bit 3  - ap_ready (Read)
 *           bit 7  - auto_restart (Read/Write)
 *           others - reserved
 * 0x00004 : Global Interrupt Enable Register
 *           bit 0  - Global Interrupt Enable (Read/Write)
 *           others - reserved
 * 0x00008 : IP Interrupt Enable Register (Read/Write)
 *           bit 0  - Channel 0 (ap_done)
 *           bit 1  - Channel 1 (ap_ready)
 *           others - reserved
 * 0x0000c : IP Interrupt Status Register (Read/TOW)
 *           bit 0  - Channel 0 (ap_done)
 *           bit 1  - Channel 1 (ap_ready)
 *           others - reserved
 * 0x00010 : Data signal of HwReg_width
 *           bit 15~0 - HwReg_width[15:0] (Read/Write)
 *           others   - reserved
 * 0x00014 : reserved
 * 0x00018 : Data signal of HwReg_height
 *           bit 15~0 - HwReg_height[15:0] (Read/Write)
 *           others   - reserved
 * 0x0001c : reserved
 * 0x00020 : Data signal of HwReg_video_format
 *           bit 15~0 - HwReg_video_format[15:0] (Read/Write)
 *           others   - reserved
 * 0x00024 : reserved
 * 0x00028 : Data signal of HwReg_background_Y_R
 *           bit 15~0 - HwReg_background_Y_R[15:0] (Read/Write)
 *           others   - reserved
 * 0x0002c : reserved
 * 0x00030 : Data signal of HwReg_background_U_G
 *           bit 15~0 - HwReg_background_U_G[15:0] (Read/Write)
 *           others   - reserved
 * 0x00034 : reserved
 * 0x00038 : Data signal of HwReg_background_V_B
 *           bit 15~0 - HwReg_background_V_B[15:0] (Read/Write)
 *           others   - reserved
 * 0x0003c : reserved
 * 0x00040 : Data signal of HwReg_layerEnable
 *           bit 15~0 - HwReg_layerEnable[15:0] (Read/Write)
 *           others   - reserved
 * 0x00044 : reserved
 * 0x00048 : Data signal of HwReg_layer1_V
 *           bit 31~0 - HwReg_layer1_V[31:0] (Read/Write)
 * 0x0004c : reserved
 * 0x00050 : Data signal of HwReg_layer2_V
 *           bit 31~0 - HwReg_layer2_V[31:0] (Read/Write)
 * 0x00054 : reserved
 * 0x00058 : Data signal of HwReg_layer3_V
 *           bit 31~0 - HwReg_layer3_V[31:0] (Read/Write)
 * 0x0005c : reserved
 * 0x00060 : Data signal of HwReg_layer4_V
 *           bit 31~0 - HwReg_layer4_V[31:0] (Read/Write)
 * 0x00064 : reserved
 * 0x00068 : Data signal of HwReg_layer5_V
 *           bit 31~0 - HwReg_layer5_V[31:0] (Read/Write)
 * 0x0006c : reserved
 * 0x00070 : Data signal of HwReg_layer6_V
 *           bit 31~0 - HwReg_layer6_V[31:0] (Read/Write)
 * 0x00074 : reserved
 * 0x00078 : Data signal of HwReg_layer7_V
 *           bit 31~0 - HwReg_layer7_V[31:0] (Read/Write)
 * 0x0007c : reserved
 * 0x00080 : Data signal of HwReg_layerAlpha_0
 *           bit 15~0 - HwReg_layerAlpha_0[15:0] (Read/Write)
 *           others   - reserved
 * 0x00084 : reserved
 * 0x00088 : Data signal of HwReg_layerAlpha_1
 *           bit 15~0 - HwReg_layerAlpha_1[15:0] (Read/Write)
 *           others   - reserved
 * 0x0008c : reserved
 * 0x00090 : Data signal of HwReg_layerAlpha_2
 *           bit 15~0 - HwReg_layerAlpha_2[15:0] (Read/Write)
 *           others   - reserved
 * 0x00094 : reserved
 * 0x00098 : Data signal of HwReg_layerAlpha_3
 *           bit 15~0 - HwReg_layerAlpha_3[15:0] (Read/Write)
 *           others   - reserved
 * 0x0009c : reserved
 * 0x000a0 : Data signal of HwReg_layerAlpha_4
 *           bit 15~0 - HwReg_layerAlpha_4[15:0] (Read/Write)
 *           others   - reserved
 * 0x000a4 : reserved
 * 0x000a8 : Data signal of HwReg_layerAlpha_5
 *           bit 15~0 - HwReg_layerAlpha_5[15:0] (Read/Write)
 *           others   - reserved
 * 0x000ac : reserved
 * 0x000b0 : Data signal of HwReg_layerAlpha_6
 *           bit 15~0 - HwReg_layerAlpha_6[15:0] (Read/Write)
 *           others   - reserved
 * 0x000b4 : reserved
 * 0x000b8 : Data signal of HwReg_layerAlpha_7
 *           bit 15~0 - HwReg_layerAlpha_7[15:0] (Read/Write)
 *           others   - reserved
 * 0x000bc : reserved
 * 0x000c0 : Data signal of HwReg_layerStartX_0
 *           bit 15~0 - HwReg_layerStartX_0[15:0] (Read/Write)
 *           others   - reserved
 * 0x000c4 : reserved
 * 0x000c8 : Data signal of HwReg_layerStartX_1
 *           bit 15~0 - HwReg_layerStartX_1[15:0] (Read/Write)
 *           others   - reserved
 * 0x000cc : reserved
 * 0x000d0 : Data signal of HwReg_layerStartX_2
 *           bit 15~0 - HwReg_layerStartX_2[15:0] (Read/Write)
 *           others   - reserved
 * 0x000d4 : reserved
 * 0x000d8 : Data signal of HwReg_layerStartX_3
 *           bit 15~0 - HwReg_layerStartX_3[15:0] (Read/Write)
 *           others   - reserved
 * 0x000dc : reserved
 * 0x000e0 : Data signal of HwReg_layerStartX_4
 *           bit 15~0 - HwReg_layerStartX_4[15:0] (Read/Write)
 *           others   - reserved
 * 0x000e4 : reserved
 * 0x000e8 : Data signal of HwReg_layerStartX_5
 *           bit 15~0 - HwReg_layerStartX_5[15:0] (Read/Write)
 *           others   - reserved
 * 0x000ec : reserved
 * 0x000f0 : Data signal of HwReg_layerStartX_6
 *           bit 15~0 - HwReg_layerStartX_6[15:0] (Read/Write)
 *           others   - reserved
 * 0x000f4 : reserved
 * 0x000f8 : Data signal of HwReg_layerStartX_7
 *           bit 15~0 - HwReg_layerStartX_7[15:0] (Read/Write)
 *           others   - reserved
 * 0x000fc : reserved
 * 0x00100 : Data signal of HwReg_layerStartY_0
 *           bit 15~0 - HwReg_layerStartY_0[15:0] (Read/Write)
 *           others   - reserved
 * 0x00104 : reserved
 * 0x00108 : Data signal of HwReg_layerStartY_1
 *           bit 15~0 - HwReg_layerStartY_1[15:0] (Read/Write)
 *           others   - reserved
 * 0x0010c : reserved
 * 0x00110 : Data signal of HwReg_layerStartY_2
 *           bit 15~0 - HwReg_layerStartY_2[15:0] (Read/Write)
 *           others   - reserved
 * 0x00114 : reserved
 * 0x00118 : Data signal of HwReg_layerStartY_3
 *           bit 15~0 - HwReg_layerStartY_3[15:0] (Read/Write)
 *           others   - reserved
 * 0x0011c : reserved
 * 0x00120 : Data signal of HwReg_layerStartY_4
 *           bit 15~0 - HwReg_layerStartY_4[15:0] (Read/Write)
 *           others   - reserved
 * 0x00124 : reserved
 * 0x00128 : Data signal of HwReg_layerStartY_5
 *           bit 15~0 - HwReg_layerStartY_5[15:0] (Read/Write)
 *           others   - reserved
 * 0x0012c : reserved
 * 0x00130 : Data signal of HwReg_layerStartY_6
 *           bit 15~0 - HwReg_layerStartY_6[15:0] (Read/Write)
 *           others   - reserved
 * 0x00134 : reserved
 * 0x00138 : Data signal of HwReg_layerStartY_7
 *           bit 15~0 - HwReg_layerStartY_7[15:0] (Read/Write)
 *           others   - reserved
 * 0x0013c : reserved
 * 0x00140 : Data signal of HwReg_layerWidth_0
 *           bit 15~0 - HwReg_layerWidth_0[15:0] (Read/Write)
 *           others   - reserved
 * 0x00144 : reserved
 * 0x00148 : Data signal of HwReg_layerWidth_1
 *           bit 15~0 - HwReg_layerWidth_1[15:0] (Read/Write)
 *           others   - reserved
 * 0x0014c : reserved
 * 0x00150 : Data signal of HwReg_layerWidth_2
 *           bit 15~0 - HwReg_layerWidth_2[15:0] (Read/Write)
 *           others   - reserved
 * 0x00154 : reserved
 * 0x00158 : Data signal of HwReg_layerWidth_3
 *           bit 15~0 - HwReg_layerWidth_3[15:0] (Read/Write)
 *           others   - reserved
 * 0x0015c : reserved
 * 0x00160 : Data signal of HwReg_layerWidth_4
 *           bit 15~0 - HwReg_layerWidth_4[15:0] (Read/Write)
 *           others   - reserved
 * 0x00164 : reserved
 * 0x00168 : Data signal of HwReg_layerWidth_5
 *           bit 15~0 - HwReg_layerWidth_5[15:0] (Read/Write)
 *           others   - reserved
 * 0x0016c : reserved
 * 0x00170 : Data signal of HwReg_layerWidth_6
 *           bit 15~0 - HwReg_layerWidth_6[15:0] (Read/Write)
 *           others   - reserved
 * 0x00174 : reserved
 * 0x00178 : Data signal of HwReg_layerWidth_7
 *           bit 15~0 - HwReg_layerWidth_7[15:0] (Read/Write)
 *           others   - reserved
 * 0x0017c : reserved
 * 0x00180 : Data signal of HwReg_layerHeight_0
 *           bit 15~0 - HwReg_layerHeight_0[15:0] (Read/Write)
 *           others   - reserved
 * 0x00184 : reserved
 * 0x00188 : Data signal of HwReg_layerHeight_1
 *           bit 15~0 - HwReg_layerHeight_1[15:0] (Read/Write)
 *           others   - reserved
 * 0x0018c : reserved
 * 0x00190 : Data signal of HwReg_layerHeight_2
 *           bit 15~0 - HwReg_layerHeight_2[15:0] (Read/Write)
 *           others   - reserved
 * 0x00194 : reserved
 * 0x00198 : Data signal of HwReg_layerHeight_3
 *           bit 15~0 - HwReg_layerHeight_3[15:0] (Read/Write)
 *           others   - reserved
 * 0x0019c : reserved
 * 0x001a0 : Data signal of HwReg_layerHeight_4
 *           bit 15~0 - HwReg_layerHeight_4[15:0] (Read/Write)
 *           others   - reserved
 * 0x001a4 : reserved
 * 0x001a8 : Data signal of HwReg_layerHeight_5
 *           bit 15~0 - HwReg_layerHeight_5[15:0] (Read/Write)
 *           others   - reserved
 * 0x001ac : reserved
 * 0x001b0 : Data signal of HwReg_layerHeight_6
 *           bit 15~0 - HwReg_layerHeight_6[15:0] (Read/Write)
 *           others   - reserved
 * 0x001b4 : reserved
 * 0x001b8 : Data signal of HwReg_layerHeight_7
 *           bit 15~0 - HwReg_layerHeight_7[15:0] (Read/Write)
 *           others   - reserved
 * 0x001bc : reserved
 * 0x001c0 : Data signal of HwReg_layerScaleFactor_0
 *           bit 7~0 - HwReg_layerScaleFactor_0[7:0] (Read/Write)
 *           others  - reserved
 * 0x001c4 : reserved
 * 0x001c8 : Data signal of HwReg_layerScaleFactor_1
 *           bit 7~0 - HwReg_layerScaleFactor_1[7:0] (Read/Write)
 *           others  - reserved
 * 0x001cc : reserved
 * 0x001d0 : Data signal of HwReg_layerScaleFactor_2
 *           bit 7~0 - HwReg_layerScaleFactor_2[7:0] (Read/Write)
 *           others  - reserved
 * 0x001d4 : reserved
 * 0x001d8 : Data signal of HwReg_layerScaleFactor_3
 *           bit 7~0 - HwReg_layerScaleFactor_3[7:0] (Read/Write)
 *           others  - reserved
 * 0x001dc : reserved
 * 0x001e0 : Data signal of HwReg_layerScaleFactor_4
 *           bit 7~0 - HwReg_layerScaleFactor_4[7:0] (Read/Write)
 *           others  - reserved
 * 0x001e4 : reserved
 * 0x001e8 : Data signal of HwReg_layerScaleFactor_5
 *           bit 7~0 - HwReg_layerScaleFactor_5[7:0] (Read/Write)
 *           others  - reserved
 * 0x001ec : reserved
 * 0x001f0 : Data signal of HwReg_layerScaleFactor_6
 *           bit 7~0 - HwReg_layerScaleFactor_6[7:0] (Read/Write)
 *           others  - reserved
 * 0x001f4 : reserved
 * 0x001f8 : Data signal of HwReg_layerScaleFactor_7
 *           bit 7~0 - HwReg_layerScaleFactor_7[7:0] (Read/Write)
 *           others  - reserved
 * 0x001fc : reserved
 * 0x00200 : Data signal of HwReg_layerVideoFormat_0
 *           bit 7~0 - HwReg_layerVideoFormat_0[7:0] (Read/Write)
 *           others  - reserved
 * 0x00204 : reserved
 * 0x00208 : Data signal of HwReg_layerVideoFormat_1
 *           bit 7~0 - HwReg_layerVideoFormat_1[7:0] (Read/Write)
 *           others  - reserved
 * 0x0020c : reserved
 * 0x00210 : Data signal of HwReg_layerVideoFormat_2
 *           bit 7~0 - HwReg_layerVideoFormat_2[7:0] (Read/Write)
 *           others  - reserved
 * 0x00214 : reserved
 * 0x00218 : Data signal of HwReg_layerVideoFormat_3
 *           bit 7~0 - HwReg_layerVideoFormat_3[7:0] (Read/Write)
 *           others  - reserved
 * 0x0021c : reserved
 * 0x00220 : Data signal of HwReg_layerVideoFormat_4
 *           bit 7~0 - HwReg_layerVideoFormat_4[7:0] (Read/Write)
 *           others  - reserved
 * 0x00224 : reserved
 * 0x00228 : Data signal of HwReg_layerVideoFormat_5
 *           bit 7~0 - HwReg_layerVideoFormat_5[7:0] (Read/Write)
 *           others  - reserved
 * 0x0022c : reserved
 * 0x00230 : Data signal of HwReg_layerVideoFormat_6
 *           bit 7~0 - HwReg_layerVideoFormat_6[7:0] (Read/Write)
 *           others  - reserved
 * 0x00234 : reserved
 * 0x00238 : Data signal of HwReg_layerVideoFormat_7
 *           bit 7~0 - HwReg_layerVideoFormat_7[7:0] (Read/Write)
 *           others  - reserved
 * 0x0023c : reserved
 * 0x00240 : Data signal of HwReg_logoStartX
 *           bit 15~0 - HwReg_logoStartX[15:0] (Read/Write)
 *           others   - reserved
 * 0x00244 : reserved
 * 0x00248 : Data signal of HwReg_logoStartY
 *           bit 15~0 - HwReg_logoStartY[15:0] (Read/Write)
 *           others   - reserved
 * 0x0024c : reserved
 * 0x00250 : Data signal of HwReg_logoWidth
 *           bit 15~0 - HwReg_logoWidth[15:0] (Read/Write)
 *           others   - reserved
 * 0x00254 : reserved
 * 0x00258 : Data signal of HwReg_logoHeight
 *           bit 15~0 - HwReg_logoHeight[15:0] (Read/Write)
 *           others   - reserved
 * 0x0025c : reserved
 * 0x00260 : Data signal of HwReg_logoScaleFactor
 *           bit 15~0 - HwReg_logoScaleFactor[15:0] (Read/Write)
 *           others   - reserved
 * 0x00264 : reserved
 * 0x00268 : Data signal of HwReg_logoAlpha
 *           bit 15~0 - HwReg_logoAlpha[15:0] (Read/Write)
 *           others   - reserved
 * 0x0026c : reserved
 * 0x00270 : Data signal of HwReg_layerStride_0
 *           bit 15~0 - HwReg_layerStride_0[15:0] (Read/Write)
 *           others   - reserved
 * 0x00274 : reserved
 * 0x00278 : Data signal of HwReg_layerStride_1
 *           bit 15~0 - HwReg_layerStride_1[15:0] (Read/Write)
 *           others   - reserved
 * 0x0027c : reserved
 * 0x00280 : Data signal of HwReg_layerStride_2
 *           bit 15~0 - HwReg_layerStride_2[15:0] (Read/Write)
 *           others   - reserved
 * 0x00284 : reserved
 * 0x00288 : Data signal of HwReg_layerStride_3
 *           bit 15~0 - HwReg_layerStride_3[15:0] (Read/Write)
 *           others   - reserved
 * 0x0028c : reserved
 * 0x00290 : Data signal of HwReg_layerStride_4
 *           bit 15~0 - HwReg_layerStride_4[15:0] (Read/Write)
 *           others   - reserved
 * 0x00294 : reserved
 * 0x00298 : Data signal of HwReg_layerStride_5
 *           bit 15~0 - HwReg_layerStride_5[15:0] (Read/Write)
 *           others   - reserved
 * 0x0029c : reserved
 * 0x002a0 : Data signal of HwReg_layerStride_6
 *           bit 15~0 - HwReg_layerStride_6[15:0] (Read/Write)
 *           others   - reserved
 * 0x002a4 : reserved
 * 0x002a8 : Data signal of HwReg_layerStride_7
 *           bit 15~0 - HwReg_layerStride_7[15:0] (Read/Write)
 *           others   - reserved
 * 0x002ac : reserved
 * 0x002b0 : Data signal of HwReg_logoClrKeyMin_R
 *           bit 7~0 - HwReg_logoClrKeyMin_R[7:0] (Read/Write)
 *           others  - reserved
 * 0x002b4 : reserved
 * 0x002b8 : Data signal of HwReg_logoClrKeyMin_G
 *           bit 7~0 - HwReg_logoClrKeyMin_G[7:0] (Read/Write)
 *           others  - reserved
 * 0x002bc : reserved
 * 0x002c0 : Data signal of HwReg_logoClrKeyMin_B
 *           bit 7~0 - HwReg_logoClrKeyMin_B[7:0] (Read/Write)
 *           others  - reserved
 * 0x002c4 : reserved
 * 0x002c8 : Data signal of HwReg_logoClrKeyMax_R
 *           bit 7~0 - HwReg_logoClrKeyMax_R[7:0] (Read/Write)
 *           others  - reserved
 * 0x002cc : reserved
 * 0x002d0 : Data signal of HwReg_logoClrKeyMax_G
 *           bit 7~0 - HwReg_logoClrKeyMax_G[7:0] (Read/Write)
 *           others  - reserved
 * 0x002d4 : reserved
 * 0x002d8 : Data signal of HwReg_logoClrKeyMax_B
 *           bit 7~0 - HwReg_logoClrKeyMax_B[7:0] (Read/Write)
 *           others  - reserved
 * 0x002dc : reserved
 * 0x10000 ~
 * 0x13fff : Memory 'HwReg_logoR_V' (4096 * 16b)
 *           Word n : bit [15: 0] - HwReg_logoR_V[2n]
 *                    bit [31:16] - HwReg_logoR_V[2n+1]
 * 0x20000 ~
 * 0x23fff : Memory 'HwReg_logoG_V' (4096 * 16b)
 *           Word n : bit [15: 0] - HwReg_logoG_V[2n]
 *                    bit [31:16] - HwReg_logoG_V[2n+1]
 * 0x30000 ~
 * 0x33fff : Memory 'HwReg_logoB_V' (4096 * 16b)
 *           Word n : bit [15: 0] - HwReg_logoB_V[2n]
 *                    bit [31:16] - HwReg_logoB_V[2n+1]
 * (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write,
 * COH = Clear on Handshake)
 */

#include <linux/io.h>

#ifndef __XV_MIXER_REGS__
#define __XV_MIXER_REGS__

static inline void reg_writel(void __iomem *base, int offset, u32 val)
{
	writel(val, base + offset);
}

/* io read operations */
static inline u32 reg_readl(void __iomem *base, int offset)
{
	return readl(base + offset);
}

/************************** Constant Definitions *****************************/
#define XVMIX_MAX_SUPPORTED_LAYERS       (9)
#define XVMIX_MAX_BPC			 (16)
#define XVMIX_MAX_BG_COLOR_BITS		 (0xFFFFFFFFFFFF)
#define XVMIX_ALPHA_MIN                  (0)
#define XVMIX_ALPHA_MAX                  (256)
#define XVMIX_LAYER_WIDTH_MIN            (64)
#define XVMIX_LAYER_HEIGHT_MIN           XVMIX_LAYER_WIDTH_MIN
#define XVMIX_LOGO_LAYER_WIDTH_MIN       (32)
#define XVMIX_LOGO_LAYER_HEIGHT_MIN      XVMIX_LOGO_LAYER_WIDTH_MIN
#define XVMIX_LOGO_LAYER_WIDTH_MAX       (256)
#define XVMIX_LOGO_LAYER_HEIGHT_MAX      XVMIX_LOGO_LAYER_WIDTH_MAX
#define XVMIX_IRQ_DONE_MASK              (0x01)
#define XVMIX_IRQ_READY_MASK             (0x02)

/**************************** Register Data **********************************/
#define XV_MIX_CTRL_ADDR_AP_CTRL                       0x00000
#define XV_MIX_CTRL_ADDR_GIE                           0x00004
#define XV_MIX_CTRL_ADDR_IER                           0x00008
#define XV_MIX_CTRL_ADDR_ISR                           0x0000c
#define XV_MIX_CTRL_ADDR_HWREG_WIDTH_DATA              0x00010
#define XV_MIX_CTRL_BITS_HWREG_WIDTH_DATA              16
#define XV_MIX_CTRL_ADDR_HWREG_HEIGHT_DATA             0x00018
#define XV_MIX_CTRL_BITS_HWREG_HEIGHT_DATA             16
#define XV_MIX_CTRL_ADDR_HWREG_VIDEO_FORMAT_DATA       0x00020
#define XV_MIX_CTRL_BITS_HWREG_VIDEO_FORMAT_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_BACKGROUND_Y_R_DATA     0x00028
#define XV_MIX_CTRL_BITS_HWREG_BACKGROUND_Y_R_DATA     16
#define XV_MIX_CTRL_ADDR_HWREG_BACKGROUND_U_G_DATA     0x00030
#define XV_MIX_CTRL_BITS_HWREG_BACKGROUND_U_G_DATA     16
#define XV_MIX_CTRL_ADDR_HWREG_BACKGROUND_V_B_DATA     0x00038
#define XV_MIX_CTRL_BITS_HWREG_BACKGROUND_V_B_DATA     16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERENABLE_DATA        0x00040
#define XV_MIX_CTRL_BITS_HWREG_LAYERENABLE_DATA        16
#define XV_MIX_CTRL_ADDR_HWREG_LAYER1_V_DATA           0x00048
#define XV_MIX_CTRL_BITS_HWREG_LAYER1_V_DATA           32
#define XV_MIX_CTRL_ADDR_HWREG_LAYER2_V_DATA           0x00050
#define XV_MIX_CTRL_BITS_HWREG_LAYER2_V_DATA           32
#define XV_MIX_CTRL_ADDR_HWREG_LAYER3_V_DATA           0x00058
#define XV_MIX_CTRL_BITS_HWREG_LAYER3_V_DATA           32
#define XV_MIX_CTRL_ADDR_HWREG_LAYER4_V_DATA           0x00060
#define XV_MIX_CTRL_BITS_HWREG_LAYER4_V_DATA           32
#define XV_MIX_CTRL_ADDR_HWREG_LAYER5_V_DATA           0x00068
#define XV_MIX_CTRL_BITS_HWREG_LAYER5_V_DATA           32
#define XV_MIX_CTRL_ADDR_HWREG_LAYER6_V_DATA           0x00070
#define XV_MIX_CTRL_BITS_HWREG_LAYER6_V_DATA           32
#define XV_MIX_CTRL_ADDR_HWREG_LAYER7_V_DATA           0x00078
#define XV_MIX_CTRL_BITS_HWREG_LAYER7_V_DATA           32
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_0_DATA       0x00080
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_0_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_1_DATA       0x00088
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_1_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_2_DATA       0x00090
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_2_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_3_DATA       0x00098
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_3_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_4_DATA       0x000a0
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_4_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_5_DATA       0x000a8
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_5_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_6_DATA       0x000b0
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_6_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_7_DATA       0x000b8
#define XV_MIX_CTRL_BITS_HWREG_LAYERALPHA_7_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_0_DATA      0x000c0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_0_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_1_DATA      0x000c8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_1_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_2_DATA      0x000d0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_2_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_3_DATA      0x000d8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_3_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_4_DATA      0x000e0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_4_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_5_DATA      0x000e8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_5_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_6_DATA      0x000f0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_6_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_7_DATA      0x000f8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTX_7_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_0_DATA      0x00100
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_0_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_1_DATA      0x00108
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_1_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_2_DATA      0x00110
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_2_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_3_DATA      0x00118
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_3_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_4_DATA      0x00120
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_4_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_5_DATA      0x00128
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_5_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_6_DATA      0x00130
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_6_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_7_DATA      0x00138
#define XV_MIX_CTRL_BITS_HWREG_LAYERSTARTY_7_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_0_DATA       0x00140
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_0_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_1_DATA       0x00148
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_1_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_2_DATA       0x00150
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_2_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_3_DATA       0x00158
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_3_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_4_DATA       0x00160
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_4_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_5_DATA       0x00168
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_5_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_6_DATA       0x00170
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_6_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_7_DATA       0x00178
#define XV_MIX_CTRL_BITS_HWREG_LAYERWIDTH_7_DATA       16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_0_DATA      0x00180
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_0_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_1_DATA      0x00188
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_1_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_2_DATA      0x00190
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_2_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_3_DATA      0x00198
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_3_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_4_DATA      0x001a0
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_4_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_5_DATA      0x001a8
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_5_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_6_DATA      0x001b0
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_6_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_7_DATA      0x001b8
#define XV_MIX_CTRL_BITS_HWREG_LAYERHEIGHT_7_DATA      16
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_0_DATA 0x001c0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_0_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_1_DATA 0x001c8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_1_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_2_DATA 0x001d0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_2_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_3_DATA 0x001d8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_3_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_4_DATA 0x001e0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_4_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_5_DATA 0x001e8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_5_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_6_DATA 0x001f0
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_6_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_7_DATA 0x001f8
#define XV_MIX_CTRL_BITS_HWREG_LAYERSCALEFACTOR_7_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_0_DATA 0x00200
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_0_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_1_DATA 0x00208
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_1_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_2_DATA 0x00210
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_2_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_3_DATA 0x00218
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_3_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_4_DATA 0x00220
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_4_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_5_DATA 0x00228
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_5_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_6_DATA 0x00230
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_6_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_7_DATA 0x00238
#define XV_MIX_CTRL_BITS_HWREG_LAYERVIDEOFORMAT_7_DATA 8
#define XV_MIX_CTRL_ADDR_HWREG_LOGOSTARTX_DATA         0x00240
#define XV_MIX_CTRL_BITS_HWREG_LOGOSTARTX_DATA         16
#define XV_MIX_CTRL_ADDR_HWREG_LOGOSTARTY_DATA         0x00248
#define XV_MIX_CTRL_BITS_HWREG_LOGOSTARTY_DATA         16
#define XV_MIX_CTRL_ADDR_HWREG_LOGOWIDTH_DATA          0x00250
#define XV_MIX_CTRL_BITS_HWREG_LOGOWIDTH_DATA          16
#define XV_MIX_CTRL_ADDR_HWREG_LOGOHEIGHT_DATA         0x00258
#define XV_MIX_CTRL_BITS_HWREG_LOGOHEIGHT_DATA         16
#define XV_MIX_CTRL_ADDR_HWREG_LOGOSCALEFACTOR_DATA    0x00260
#define XV_MIX_CTRL_BITS_HWREG_LOGOSCALEFACTOR_DATA    16
#define XV_MIX_CTRL_ADDR_HWREG_LOGOALPHA_DATA          0x00268
#define XV_MIX_CTRL_BITS_HWREG_LOGOALPHA_DATA          16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_0_DATA           0x00270
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_0_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_1_DATA           0x00278
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_1_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_2_DATA           0x00280
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_2_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_3_DATA           0x00288
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_3_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_4_DATA           0x00290
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_4_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_5_DATA           0x00298
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_5_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_6_DATA           0x002a0
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_6_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_STRIDE_7_DATA           0x002a8
#define XV_MIX_CTRL_BITS_HWREG_STRIDE_7_DATA           16
#define XV_MIX_CTRL_ADDR_HWREG_LOGOCLRKEYMIN_R_DATA    0x002b0
#define XV_MIX_CTRL_BITS_HWREG_LOGOCLRKEYMIN_R_DATA    8
#define XV_MIX_CTRL_ADDR_HWREG_LOGOCLRKEYMIN_G_DATA    0x002b8
#define XV_MIX_CTRL_BITS_HWREG_LOGOCLRKEYMIN_G_DATA    8
#define XV_MIX_CTRL_ADDR_HWREG_LOGOCLRKEYMIN_B_DATA    0x002c0
#define XV_MIX_CTRL_BITS_HWREG_LOGOCLRKEYMIN_B_DATA    8
#define XV_MIX_CTRL_ADDR_HWREG_LOGOCLRKEYMAX_R_DATA    0x002c8
#define XV_MIX_CTRL_BITS_HWREG_LOGOCLRKEYMAX_R_DATA    8
#define XV_MIX_CTRL_ADDR_HWREG_LOGOCLRKEYMAX_G_DATA    0x002d0
#define XV_MIX_CTRL_BITS_HWREG_LOGOCLRKEYMAX_G_DATA    8
#define XV_MIX_CTRL_ADDR_HWREG_LOGOCLRKEYMAX_B_DATA    0x002d8
#define XV_MIX_CTRL_BITS_HWREG_LOGOCLRKEYMAX_B_DATA    8
#define XV_MIX_CTRL_ADDR_HWREG_LOGOR_V_BASE            0x10000
#define XV_MIX_CTRL_ADDR_HWREG_LOGOR_V_HIGH            0x13fff
#define XV_MIX_CTRL_WIDTH_HWREG_LOGOR_V                16
#define XV_MIX_CTRL_DEPTH_HWREG_LOGOR_V                4096
#define XV_MIX_CTRL_ADDR_HWREG_LOGOG_V_BASE            0x20000
#define XV_MIX_CTRL_ADDR_HWREG_LOGOG_V_HIGH            0x23fff
#define XV_MIX_CTRL_WIDTH_HWREG_LOGOG_V                16
#define XV_MIX_CTRL_DEPTH_HWREG_LOGOG_V                4096
#define XV_MIX_CTRL_ADDR_HWREG_LOGOB_V_BASE            0x30000
#define XV_MIX_CTRL_ADDR_HWREG_LOGOB_V_HIGH            0x33fff
#define XV_MIX_CTRL_WIDTH_HWREG_LOGOB_V                16
#define XV_MIX_CTRL_DEPTH_HWREG_LOGOB_V                4096
#define XV_MIX_CTRL_ADDR_HWREG_LOGOA_V_BASE            0x40000
#define XV_MIX_CTRL_ADDR_HWREG_LOGOA_V_HIGH            0x43fff
#define XV_MIX_CTRL_WIDTH_HWREG_LOGOA_V                16
#define XV_MIX_CTRL_DEPTH_HWREG_LOGOA_V                4096

#endif /* __XV_MIXER_REGS__ */
