/*
 * usr/bin2asm.c
 *
 * Copyright 2007 Xilinx, Inc.
 *
 * This file is licensed under the terms of the GNU General Public License
 * version 2.  This program is licensed "as is" without any warranty of any
 * kind, whether express or implied.
 */

#include <fcntl.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
	FILE *in_file;
	int in_byte;

	if (argc != 2)
		return -1;

	if ((in_file = fopen(argv[1], "rb")) == NULL)
		return -1;

	printf("\n/* The following code was "
		"automatically generated by bin2asm. Do not edit. */\n\n");

	while((in_byte=fgetc(in_file)) != EOF)
		printf("\t.byte 0x%X\n", in_byte);

	printf("\n/* End of the generated code */\n");

	fclose(in_file);
	return 0;
}
