
ccflags-$(CONFIG_PMODS_DEBUG)  += -DDEBUG

obj-$(CONFIG_PMODOLED) += pmodoled-gpio.o
obj-$(CONFIG_PMODCLS) += pmodcls.o
obj-$(CONFIG_PMODCLP) += pmodclp.o
obj-$(CONFIG_PMODDA1) += pmodda1.o
obj-$(CONFIG_PMODAD1) += pmodad1.o
