#ifndef XLNK_EVENT_TRACER_TYPE_H
#define XLNK_EVENT_TRACER_TYPE_H

#define XLNK_ET_USERSPACE_BEFORE_ACC_TRANSFER_CALL	50
#define XLNK_ET_USERSPACE_BEFORE_PORT_WAIT4COMPLETION	51

#define XLNK_ET_USERSPACE_BEFORE_DMA_SUBMIT		100
#define XLNK_ET_USERSPACE_AFTER_DMA_SUBMIT		101
#define XLNK_ET_USERSPACE_BEFORE_DMA_WAIT4COMPLETION	102
#define XLNK_ET_USERSPACE_AFTER_DMA_WAIT4COMPLETION	103

#define XLNK_ET_KERNEL_ENTER_IOCTL			5000
#define XLNK_ET_KERNEL_LEAVE_IOCTL			5001
#define XLNK_ET_KERNEL_ENTER_DMA_SUBMIT			5002
#define XLNK_ET_KERNEL_LEAVE_DMA_SUBMIT			5003
#define XLNK_ET_KERNEL_BEFORE_PIN_USER_PAGE		5004
#define XLNK_ET_KERNEL_BEFORE_GET_USER_PAGES		5005
#define XLNK_ET_KERNEL_AFTER_GET_USER_PAGES		5006
#define XLNK_ET_KERNEL_AFTER_PIN_USER_PAGE		5007
#define XLNK_ET_KERNEL_BEFORE_DMA_MAP_SG		5008
#define XLNK_ET_KERNEL_AFTER_DMA_MAP_SG			5009
#define XLNK_ET_KERNEL_BEFORE_DMA_SETUP_BD		5010
#define XLNK_ET_KERNEL_AFTER_DMA_KICKOFF		5011
#define XLNK_ET_KERNEL_AFTER_DMA_SETUP_BD		5012
#define XLNK_ET_KERNEL_ENTER_DMA_WAIT			5013
#define XLNK_ET_KERNEL_BEFORE_DMA_UNMAP_SG		5014
#define XLNK_ET_KERNEL_AFTER_DMA_UNMAP_SG		5015
#define XLNK_ET_KERNEL_LEAVE_DMA_WAIT			5016


#define XLNK_ET_KERNEL_DMA_MM2S_INTR			5100
#define XLNK_ET_KERNEL_DMA_MM2S_HALF_BOTTOM_START	5101
#define XLNK_ET_KERNEL_DMA_MM2S_HALF_BOTTOM_END		5102
#define XLNK_ET_KERNEL_DMA_S2MM_INTR			5110
#define XLNK_ET_KERNEL_DMA_S2MM_HALF_BOTTOM_START	5111
#define XLNK_ET_KERNEL_DMA_S2MM_HALF_BOTTOM_END		5112

#endif

