xlnx_drm-objs += xlnx_crtc.o xlnx_drv.o xlnx_fb.o xlnx_gem.o
xlnx_drm-$(CONFIG_DRM_XLNX_BRIDGE) += xlnx_bridge.o
obj-$(CONFIG_DRM_XLNX) += xlnx_drm.o

obj-$(CONFIG_DRM_XLNX_BRIDGE_CSC) += xlnx_csc.o

obj-$(CONFIG_DRM_XLNX_BRIDGE_SCALER) += xlnx_scaler.o

obj-$(CONFIG_DRM_XLNX_BRIDGE_VTC) += xlnx_vtc.o

obj-$(CONFIG_DRM_XLNX_DPTX) += xlnx_dptx.o

obj-$(CONFIG_DRM_XLNX_DSI) += xlnx_dsi.o

obj-$(CONFIG_DRM_XLNX_MIXER) += xlnx_mixer.o

obj-$(CONFIG_DRM_XLNX_PL_DISP) += xlnx_pl_disp.o

xlnx-sdi-objs += xlnx_sdi.o xlnx_sdi_timing.o
obj-$(CONFIG_DRM_XLNX_SDI) += xlnx-sdi.o

zynqmp-dpsub-objs += zynqmp_disp.o zynqmp_dpsub.o zynqmp_dp.o
obj-$(CONFIG_DRM_ZYNQMP_DPSUB) += zynqmp-dpsub.o
