# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Xilinx AI engine device driver
#

obj-$(CONFIG_XILINX_AIE)	+= xilinx-aie.o

xilinx-aie-$(CONFIG_XILINX_AIE) := ai-engine-aie.o \
				   ai-engine-clock.o \
				   ai-engine-dev.o \
				   ai-engine-dma.o \
				   ai-engine-fpga.o \
				   ai-engine-interrupt.o \
				   ai-engine-mem.o \
				   ai-engine-part.o \
				   ai-engine-res.o \
				   ai-engine-reset.o
