#
# Makefile for the PCI specific kernel interface routines under Linux.
#

obj-y += pci.o
obj-$(CONFIG_PCI_ALTPCI) += altpci.o
obj-$(CONFIG_PCI_ALTPCI) += setup-irq.o
obj-$(CONFIG_PCI_AUTO) += pci-auto.o
