obj-$(CONFIG_DRM_XLNX_HDCP) += xhdcp2x_tx.o \
				xhdcp1x_tx.o \
				xlnx_hdcp1x_keymngt.o \
				xlnx_hdcp1x_tx.o \
				xlnx_hdcp2x_tx.o \
				xlnx_hdcp_sha1.o \
				xlnx_hdcp2x_crypt.o xlnx_hdcp_tx.o
