# $Id: Makefile,v 1.1 2006/07/05 06:23:18 gerg Exp $
# Makefile for the linux Sparc-specific parts of the memory manager.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definition is now in the main makefile...

obj-y	:= init.o ioremap.o extable.o memory.o
obj-y	+= dma-noncoherent.o

