#
# Copyright (C) 2005 Microtronix Datacom Ltd
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU Library General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more
# details.

####CSRC := $(wildcard *.c)
####lib-y  =$(patsubst %.c,%.o, $(CSRC))
####wapos!
lib-y  =checksum.o string.o memcpy.o
