# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Radio over Ethernet Framer driver
#
obj-$(CONFIG_XROE_FRAMER)	:= framer.o

framer-objs := 	xroe_framer.o \
		sysfs_xroe.o \
		sysfs_xroe_framer_ipv4.o \
		sysfs_xroe_framer_ipv6.o \
		sysfs_xroe_framer_udp.o \
		sysfs_xroe_framer_stats.o
