# SPDX-License-Identifier: GPL-2.0
# Makefile for Xilinx firmwares

obj-$(CONFIG_ZYNQMP_FIRMWARE) += zynqmp-core.o zynqmp-pm.o zynqmp-sem.o zynqmp-fpga.o zynqmp-nvm.o zynqmp-pdi.o zynqmp-crypto.o
obj-$(CONFIG_ZYNQMP_FIRMWARE_DEBUG) += zynqmp-debug.o
obj-$(CONFIG_ZYNQMP_FIRMWARE_SECURE) += zynqmp-secure.o
