/* SPDX-License-Identifier: GPL-2.0 */
/*
 * AMD Versal Gen 2 SCMI Power Domain IDs.
 * Use with the AMD Versal Gen 2 firmware driver
 *
 * Copyright (C) 2026, Advanced Micro Devices, Inc.
 *
 * Jay Buddhabhatti <jay.buddhabhatti@amd.com>
 */

#ifndef __FIRMWARE_VERSAL2_SCMI_POWER_H__
#define __FIRMWARE_VERSAL2_SCMI_POWER_H__

/*
 * SCMI Power Domain Ids
 *
 * Compact IDs which name the devices exposed by the SCMI server in EL3. The
 * numbering is a fixed interface, so it has to stay in step with that server.
 */
#define SCMI_PD_VERSAL2_DEV_RPU_A_0	0
#define SCMI_PD_VERSAL2_DEV_RPU_A_1	1
#define SCMI_PD_VERSAL2_DEV_RPU_B_0	2
#define SCMI_PD_VERSAL2_DEV_RPU_B_1	3
#define SCMI_PD_VERSAL2_DEV_RPU_C_0	4
#define SCMI_PD_VERSAL2_DEV_RPU_C_1	5
#define SCMI_PD_VERSAL2_DEV_RPU_D_0	6
#define SCMI_PD_VERSAL2_DEV_RPU_D_1	7
#define SCMI_PD_VERSAL2_DEV_RPU_E_0	8
#define SCMI_PD_VERSAL2_DEV_RPU_E_1	9
#define SCMI_PD_VERSAL2_DEV_USB_0	10
#define SCMI_PD_VERSAL2_DEV_GEM_0	11
#define SCMI_PD_VERSAL2_DEV_GEM_1	12
#define SCMI_PD_VERSAL2_DEV_SPI_0	13
#define SCMI_PD_VERSAL2_DEV_SPI_1	14
#define SCMI_PD_VERSAL2_DEV_I2C_0	15
#define SCMI_PD_VERSAL2_DEV_I2C_1	16
#define SCMI_PD_VERSAL2_DEV_CAN_FD_0	17
#define SCMI_PD_VERSAL2_DEV_CAN_FD_1	18
#define SCMI_PD_VERSAL2_DEV_UART_0	19
#define SCMI_PD_VERSAL2_DEV_UART_1	20
#define SCMI_PD_VERSAL2_DEV_GPIO	21
#define SCMI_PD_VERSAL2_DEV_TTC_0	22
#define SCMI_PD_VERSAL2_DEV_TTC_1	23
#define SCMI_PD_VERSAL2_DEV_TTC_2	24
#define SCMI_PD_VERSAL2_DEV_TTC_3	25
#define SCMI_PD_VERSAL2_DEV_SWDT_LPD	26
#define SCMI_PD_VERSAL2_DEV_OSPI	27
#define SCMI_PD_VERSAL2_DEV_QSPI	28
#define SCMI_PD_VERSAL2_DEV_GPIO_PMC	29
#define SCMI_PD_VERSAL2_DEV_I2C_PMC	30
#define SCMI_PD_VERSAL2_DEV_SDIO_0	31
#define SCMI_PD_VERSAL2_DEV_SDIO_1	32
#define SCMI_PD_VERSAL2_DEV_RTC		33
#define SCMI_PD_VERSAL2_DEV_ADMA_0	34
#define SCMI_PD_VERSAL2_DEV_ADMA_1	35
#define SCMI_PD_VERSAL2_DEV_ADMA_2	36
#define SCMI_PD_VERSAL2_DEV_ADMA_3	37
#define SCMI_PD_VERSAL2_DEV_ADMA_4	38
#define SCMI_PD_VERSAL2_DEV_ADMA_5	39
#define SCMI_PD_VERSAL2_DEV_ADMA_6	40
#define SCMI_PD_VERSAL2_DEV_ADMA_7	41
#define SCMI_PD_VERSAL2_DEV_USB_1	42
#define SCMI_PD_VERSAL2_DEV_LPD_SWDT_0	43
#define SCMI_PD_VERSAL2_DEV_LPD_SWDT_1	44
#define SCMI_PD_VERSAL2_DEV_FPD_SWDT_0	45
#define SCMI_PD_VERSAL2_DEV_FPD_SWDT_1	46
#define SCMI_PD_VERSAL2_DEV_FPD_SWDT_2	47
#define SCMI_PD_VERSAL2_DEV_FPD_SWDT_3	48
#define SCMI_PD_VERSAL2_DEV_UFS		49
#define SCMI_PD_VERSAL2_DEV_I2C_2	50
#define SCMI_PD_VERSAL2_DEV_I2C_3	51
#define SCMI_PD_VERSAL2_DEV_I2C_4	52
#define SCMI_PD_VERSAL2_DEV_I2C_5	53
#define SCMI_PD_VERSAL2_DEV_I2C_6	54
#define SCMI_PD_VERSAL2_DEV_I2C_7	55
#define SCMI_PD_VERSAL2_DEV_CAN_FD_2	56
#define SCMI_PD_VERSAL2_DEV_CAN_FD_3	57
#define SCMI_PD_VERSAL2_DEV_TTC_4	58
#define SCMI_PD_VERSAL2_DEV_TTC_5	59
#define SCMI_PD_VERSAL2_DEV_TTC_6	60
#define SCMI_PD_VERSAL2_DEV_TTC_7	61
#define SCMI_PD_VERSAL2_DEV_MMI_USB_DRD	62
#define SCMI_PD_VERSAL2_DEV_MMI_GPU	63
#define SCMI_PD_VERSAL2_DEV_MMI_DC	64
#define SCMI_PD_VERSAL2_DEV_MMI_HDCP	65
#define SCMI_PD_VERSAL2_DEV_MMI_DP	66
#define SCMI_PD_VERSAL2_DEV_MMI_GEM	67
#define SCMI_PD_VERSAL2_DEV_TCM_A_0A	68
#define SCMI_PD_VERSAL2_DEV_TCM_A_0B	69
#define SCMI_PD_VERSAL2_DEV_TCM_A_0C	70
#define SCMI_PD_VERSAL2_DEV_TCM_A_1A	71
#define SCMI_PD_VERSAL2_DEV_TCM_A_1B	72
#define SCMI_PD_VERSAL2_DEV_TCM_A_1C	73
#define SCMI_PD_VERSAL2_DEV_TCM_B_0A	74
#define SCMI_PD_VERSAL2_DEV_TCM_B_0B	75
#define SCMI_PD_VERSAL2_DEV_TCM_B_0C	76
#define SCMI_PD_VERSAL2_DEV_TCM_B_1A	77
#define SCMI_PD_VERSAL2_DEV_TCM_B_1B	78
#define SCMI_PD_VERSAL2_DEV_TCM_B_1C	79
#define SCMI_PD_VERSAL2_DEV_TCM_C_0A	80
#define SCMI_PD_VERSAL2_DEV_TCM_C_0B	81
#define SCMI_PD_VERSAL2_DEV_TCM_C_0C	82
#define SCMI_PD_VERSAL2_DEV_TCM_C_1A	83
#define SCMI_PD_VERSAL2_DEV_TCM_C_1B	84
#define SCMI_PD_VERSAL2_DEV_TCM_C_1C	85
#define SCMI_PD_VERSAL2_DEV_TCM_D_0A	86
#define SCMI_PD_VERSAL2_DEV_TCM_D_0B	87
#define SCMI_PD_VERSAL2_DEV_TCM_D_0C	88
#define SCMI_PD_VERSAL2_DEV_TCM_D_1A	89
#define SCMI_PD_VERSAL2_DEV_TCM_D_1B	90
#define SCMI_PD_VERSAL2_DEV_TCM_D_1C	91
#define SCMI_PD_VERSAL2_DEV_TCM_E_0A	92
#define SCMI_PD_VERSAL2_DEV_TCM_E_0B	93
#define SCMI_PD_VERSAL2_DEV_TCM_E_0C	94
#define SCMI_PD_VERSAL2_DEV_TCM_E_1A	95
#define SCMI_PD_VERSAL2_DEV_TCM_E_1B	96
#define SCMI_PD_VERSAL2_DEV_TCM_E_1C	97
#define SCMI_PD_VERSAL2_DEV_EIO_UART_0	98
#define SCMI_PD_VERSAL2_DEV_EIO_UART_1	99
#define SCMI_PD_VERSAL2_DEV_EIO_UART_2	100
#define SCMI_PD_VERSAL2_DEV_EIO_SPI_0	101
#define SCMI_PD_VERSAL2_DEV_EIO_SPI_1	102
#define SCMI_PD_VERSAL2_DEV_EIO_SPI_2	103
#define SCMI_PD_VERSAL2_DEV_EIO_SPI_3	104
#define SCMI_PD_VERSAL2_DEV_GPIO_EIO	105

#endif /* __FIRMWARE_VERSAL2_SCMI_POWER_H__ */
