ccflags-y := -Iinclude/drm

ch7006-y := ch7006_drv.o ch7006_mode.o
obj-$(CONFIG_DRM_I2C_CH7006) += ch7006.o

sil164-y := sil164_drv.o
obj-$(CONFIG_DRM_I2C_SIL164) += sil164.o

tda998x-y := tda998x_drv.o
obj-$(CONFIG_DRM_I2C_NXP_TDA998X) += tda998x.o

adv7511-y := adv7511_core.o adv7511_audio.o
obj-$(CONFIG_DRM_ENCODER_ADV7511) += adv7511.o
