#
# Makefile for the linux kernel.
#

# Object file lists.

# obj-$(CONFIG_SERIAL_S3C44B0X)	+= serial_core_44b0x.o s3c44b0.o
obj-$(CONFIG_SERIAL_S3C44B0X)	+= console.o
obj-$(CONFIG_ETH_RTL8019AS)	+= rtl8019.o
obj-$(CONFIG_S3C44B0X_GPIO_LED)	+= led.o
