obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-pcm.o
obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-codec.o
obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-card.o
snd-soc-xlnx-i2s-objs      := xlnx_i2s.o
obj-$(CONFIG_SND_SOC_XILINX_I2S) += snd-soc-xlnx-i2s.o
