obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-pcm.o
obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-codec.o
obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-card.o
obj-$(CONFIG_SND_SOC_XILINX_AUDIO_FORMATTER) += xlnx_formatter_pcm.o
obj-$(CONFIG_SND_SOC_XILINX_SDI) += xlnx_sdi_audio.o
obj-$(CONFIG_SND_SOC_XILINX_I2S) += xlnx_i2s.o
obj-$(CONFIG_SND_SOC_XILINX_PL_SND_CARD) += xlnx_pl_snd_card.o
