obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-pcm.o
obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-codec.o
obj-$(CONFIG_SND_SOC_XILINX_DP) += xilinx-dp-card.o
obj-$(CONFIG_SND_SOC_XILINX_AUDIO_FORMATTER) += xlnx_formatter_pcm.o
