# File: drivers/net/arm/Makefile
#
# Makefile for the ARM network device drivers
#

obj-$(CONFIG_ARM_AM79C961A)	+= am79c961a.o
obj-$(CONFIG_ARM_ETHERH)	+= etherh.o
obj-$(CONFIG_ARM_ETHER3)	+= ether3.o
obj-$(CONFIG_ARM_ETHER1)	+= ether1.o
obj-$(CONFIG_ARM_AT91_ETHER)	+= at91_ether.o
obj-$(CONFIG_EP93XX_ETH)	+= ep93xx_eth.o
obj-$(CONFIG_ETH_S3C4510B)	+= eth_s3c4510b.o
obj-$(CONFIG_P2001_ETH)		+= p2001_eth.o
