obj-$(CONFIG_XILINX_AXIDMA) += xilinx_axidma.o
obj-$(CONFIG_XILINX_DMATEST) += axidmatest.o
obj-$(CONFIG_XILINX_AXIVDMA) += xilinx_axivdma.o
obj-$(CONFIG_XILINX_VDMATEST) += vdmatest.o
obj-$(CONFIG_XILINX_AXICDMA) += xilinx_axicdma.o
obj-$(CONFIG_XILINX_CDMATEST) += cdmatest.o
