# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_XILINX_DMATEST) += axidmatest.o
obj-$(CONFIG_XILINX_VDMATEST) += vdmatest.o
obj-$(CONFIG_XILINX_DMA) += xilinx_dma.o
obj-$(CONFIG_XILINX_ZYNQMP_DMA) += zynqmp_dma.o
obj-$(CONFIG_XILINX_ZYNQMP_DPDMA) += xilinx_dpdma.o
