obj-$(CONFIG_XILINX_AXIDMA) += xilinx_dma.o
obj-$(CONFIG_XILINX_DMATEST) += axidmatest.o
obj-$(CONFIG_XILINX_VDMATEST) += vdmatest.o
obj-$(CONFIG_XILINX_AXICDMA) += xilinx_cdma.o
obj-$(CONFIG_XILINX_CDMATEST) += cdmatest.o
obj-$(CONFIG_XILINX_DPDMA) += xilinx_dpdma.o
obj-$(CONFIG_XILINX_VDMA) += xilinx_vdma.o
obj-$(CONFIG_XILINX_ZYNQMP_DMA) += zynqmp_dma.o
