xilinx-scd-objs += xilinx-scenechange.o xilinx-scenechange-channel.o \
		   xilinx-scenechange-dma.o
xilinx-video-objs += xilinx-dma.o xilinx-vip.o xilinx-vipp.o

obj-$(CONFIG_VIDEO_XILINX) += xilinx-video.o
obj-$(CONFIG_VIDEO_XILINX_AXI4S_SWITCH) += xilinx-axis-switch.o
obj-$(CONFIG_VIDEO_XILINX_CFA) += xilinx-cfa.o
obj-$(CONFIG_VIDEO_XILINX_CRESAMPLE) += xilinx-cresample.o
obj-$(CONFIG_VIDEO_XILINX_CSI2RXSS) += xilinx-csi2rxss.o
obj-$(CONFIG_VIDEO_XILINX_DEMOSAIC) += xilinx-demosaic.o
obj-$(CONFIG_VIDEO_XILINX_GAMMA) += xilinx-gamma.o
obj-$(CONFIG_VIDEO_XILINX_HLS) += xilinx-hls.o
obj-$(CONFIG_VIDEO_XILINX_M2M) += xilinx-m2m.o
obj-$(CONFIG_VIDEO_XILINX_MULTISCALER) += xilinx-multi-scaler.o
obj-$(CONFIG_VIDEO_XILINX_REMAPPER) += xilinx-remapper.o
obj-$(CONFIG_VIDEO_XILINX_RGB2YUV) += xilinx-rgb2yuv.o
obj-$(CONFIG_VIDEO_XILINX_SCALER) += xilinx-scaler.o
obj-$(CONFIG_VIDEO_XILINX_SCD) += xilinx-scd.o
obj-$(CONFIG_VIDEO_XILINX_SDIRXSS) += xilinx-sdirxss.o
obj-$(CONFIG_VIDEO_XILINX_SWITCH) += xilinx-switch.o
obj-$(CONFIG_VIDEO_XILINX_TPG) += xilinx-tpg.o
obj-$(CONFIG_VIDEO_XILINX_VPSS_CSC) += xilinx-vpss-csc.o
obj-$(CONFIG_VIDEO_XILINX_VPSS_SCALER) += xilinx-vpss-scaler.o
obj-$(CONFIG_VIDEO_XILINX_VTC) += xilinx-vtc.o
