xilinx-axi-video-objs += xilinx-dma.o xilinx-vip.o xilinx-vipp.o

obj-$(CONFIG_VIDEO_XILINX) += xilinx-axi-video.o
obj-$(CONFIG_VIDEO_XILINX_CFA) += xilinx-cfa.o
obj-$(CONFIG_VIDEO_XILINX_CRESAMPLE) += xilinx-cresample.o
obj-$(CONFIG_VIDEO_XILINX_RGB2YUV) += xilinx-rgb2yuv.o
obj-$(CONFIG_VIDEO_XILINX_SCALER) += xilinx-scaler.o
obj-$(CONFIG_VIDEO_XILINX_REMAPPER) += xilinx-remapper.o
obj-$(CONFIG_VIDEO_XILINX_SWITCH) += xilinx-switch.o
obj-$(CONFIG_VIDEO_XILINX_TPG) += xilinx-tpg.o
obj-$(CONFIG_VIDEO_XILINX_VTC) += xilinx-vtc.o
