/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Xilinx DP RX Subsystem register map
 *
 * Copyright (C) 2020 Xilinx, Inc.
 * Copyright (C) 2024 - 2026, Advanced Micro Devices, Inc. All rights reserved.
 *
 * Author: Katta Dhanunjanrao <katta.dhanunjanrao@amd.com>
 */

#ifndef __XILINX_DPRXSS_HW_H__
#define __XILINX_DPRXSS_HW_H__

#include <linux/bits.h>
#include <linux/units.h>

/* DP Rx subsystem register map, bitmask, and offsets. */
#define XDPRX_LINK_ENABLE_REG		0x000
#define XDPRX_AUX_CLKDIV_REG		0x004
#define XDPRX_AUX_DEFER_COUNT		6
#define XDPRX_AUX_DEFER_SHIFT		24
#define XDPRX_AUX_DEFER_MASK		GENMASK(27, 24)

#define XDPRX_LINERST_DIS_REG		0x008
#define XDPRX_DTG_REG			0x00c
#define XDPRX_DTG_DIS_MASK		BIT(0)
#define XDPRX_VSCEXT_VESA_SDP_SUPPORTED	BIT(2)

#define XDPRX_PIXEL_WIDTH_REG		0x010
#define XDPRX_INTR_MASK_REG		0x014
#define XDPRX_INTR_POWER_MASK		BIT(1)
#define XDPRX_INTR_NOVID_MASK		BIT(2)
#define XDPRX_INTR_VBLANK_MASK		BIT(3)
#define XDPRX_INTR_TRLOST_MASK		BIT(4)
#define XDPRX_INTR_VID_MASK		BIT(6)
#define XDPRX_INTR_AUDIO_MASK		BIT(8)
#define XDPRX_INTR_TRDONE_MASK		BIT(14)
#define XDPRX_INTR_BWCHANGE_MASK	BIT(15)
#define XDPRX_INTR_TP1_MASK		BIT(16)
#define XDPRX_INTR_TP2_MASK		BIT(17)
#define XDPRX_INTR_TP3_MASK		BIT(18)
#define XDPRX_INTR_HDCP1X_DBG_WRITE_MASK	BIT(19)
#define XDPRX_INTR_HDCP1X_AKSV_WRITE_MASK	BIT(20)
#define XDPRX_INTR_HDCP1X_AN_WRITE_MASK		BIT(21)
#define XDPRX_INTR_HDCP1X_AINFO_WRITE_MASK	BIT(22)
#define XDPRX_INTR_HDCP1X_RO_READ_MASK		BIT(23)
#define XDPRX_INTR_HDCP1X_BINFO_READ_MASK	BIT(24)
#define XDPRX_INTR_HDCP1X_MASK_ALL	(XDPRX_INTR_HDCP1X_DBG_WRITE_MASK | \
					 XDPRX_INTR_HDCP1X_AKSV_WRITE_MASK | \
					 XDPRX_INTR_HDCP1X_AN_WRITE_MASK | \
					 XDPRX_INTR_HDCP1X_AINFO_WRITE_MASK | \
					 XDPRX_INTR_HDCP1X_RO_READ_MASK | \
					 XDPRX_INTR_HDCP1X_BINFO_READ_MASK)
#define XDPRX_INTR_HDCP2X_AKE_INIT_MASK		BIT(0)
#define XDPRX_INTR_HDCP2X_AKE_NO_STORED_KM_MASK	BIT(1)
#define XDPRX_INTR_HDCP2X_AKE_STORED_KM_MASK	BIT(2)
#define XDPRX_INTR_HDCP2X_LC_INIT_MASK		BIT(3)
#define XDPRX_INTR_HDCP2X_SKE_SEND_EKS_MASK	BIT(4)
#define XDPRX_INTR_HDCP2X_DBG_WRITE_MASK		BIT(5)
#define XDPRX_INTR_HDCP2X_HPRIME_READ_DONE_MASK	BIT(6)
#define XDPRX_INTR_HDCP2X_PAIRING_INFO_READ_MASK	BIT(7)
#define XDPRX_INTR_HDCP2X_STREAM_TYPE_MASK	BIT(8)
#define XDPRX_INTR_HDCP2X_RPTR_RCVID_LIST_ACK_MASK	BIT(9)
#define XDPRX_INTR_HDCP2X_RPTR_STREAM_MANAGE_MASK	BIT(10)
#define XDPRX_INTR_HDCP2X_MASK_ALL (XDPRX_INTR_HDCP2X_AKE_INIT_MASK | \
				XDPRX_INTR_HDCP2X_AKE_NO_STORED_KM_MASK | \
				XDPRX_INTR_HDCP2X_AKE_STORED_KM_MASK | \
				XDPRX_INTR_HDCP2X_LC_INIT_MASK | \
				XDPRX_INTR_HDCP2X_SKE_SEND_EKS_MASK | \
				XDPRX_INTR_HDCP2X_DBG_WRITE_MASK | \
				XDPRX_INTR_HDCP2X_HPRIME_READ_DONE_MASK | \
				XDPRX_INTR_HDCP2X_PAIRING_INFO_READ_MASK | \
				XDPRX_INTR_HDCP2X_STREAM_TYPE_MASK | \
				XDPRX_INTR_HDCP2X_RPTR_RCVID_LIST_ACK_MASK | \
				XDPRX_INTR_HDCP2X_RPTR_STREAM_MANAGE_MASK)
#define XDPRX_HDCP2X_REG_OFFSET		0x8000
#define XDPRX_HDCP_TIMER_OFFSET		0x3000
#define XDPRX_HDCP2X_TABLE		0x1000

#define XDPRX_INTR_LINKQUAL_MASK	BIT(29)
#define XDPRX_INTR_UNPLUG_MASK		BIT(31)
#define XDPRX_INTR_CRCTST_MASK		BIT(30)
#define XDPRX_INTR_TRNG_MASK		(XDPRX_INTR_TP1_MASK | \
					 XDPRX_INTR_TP2_MASK | \
					 XDPRX_INTR_TP3_MASK | \
					 XDPRX_INTR_POWER_MASK | \
					 XDPRX_INTR_CRCTST_MASK | \
					 XDPRX_INTR_BWCHANGE_MASK)
#define XDPRX_INTR_ACCESS_LANE_SET_MASK		BIT(30)
#define XDPRX_INTR_TP4_MASK			BIT(31)
#define XDPRX_INTR_ACCESS_LINK_QUAL_MASK	BIT(29)
#define XDPRX_INTR_ACCESS_ERR_CNT_MASK		BIT(28)
#define XDPRX_INTR_TRNG_MASK_1		(XDPRX_INTR_TP4_MASK | \
					 XDPRX_INTR_ACCESS_LANE_SET_MASK | \
					 XDPRX_INTR_ACCESS_LINK_QUAL_MASK | \
					 XDPRX_INTR_ACCESS_ERR_CNT_MASK)
#define XDPRX_INTR_ALL_MASK		GENMASK(31, 0)
#define XDPRX_INTR_ALL_MASK_1		GENMASK(31, 0)

#define XDPRX_SOFT_RST_REG		0x01c
#define XDPRX_SOFT_RST_REG_HDCP2X_MASK	BIT(9)
#define XDPRX_SOFT_VIDRST_MASK		BIT(0)
#define XDPRX_SOFT_AUXRST_MASK		BIT(7)

#define XDPRX_HPD_INTR_REG		0x02c
#define XDPRX_HPD_INTR_MASK		BIT(0)
#define XDPRX_HPD_PULSE_MASK		GENMASK(31, 16)

#define XDPRX_INTR_CAUSE_REG		0x040
#define XDPRX_INTR_MASK_1_REG		0x044
#define XDPRX_INTR_CAUSE_1_REG		0x048
#define XDPRX_INTR_CAUSE_2_REG		0x070
#define XDPRX_INTR_MASK_2_REG		0x05c
#define XDPRX_MST_ALLOC			0x06c
#define XDPRX_CRC_CONFIG_REG		0x074
#define XDPRX_CRC_EN_MASK		BIT(5)

#define XDPRX_LOCAL_EDID_REG		0x084
#define XDPRX_DEVICE_SERVICE_IRQ	0x090
#define XDPRX_DEVICE_SERVICE_IRQ_CP_IRQ_MASK	BIT(2)
#define XDPRX_DEVICE_SERVICE_IRQ_NEW_DOWN_REPLY_MASK	BIT(4)
#define XDPRX_VIDEO_UNSUPPORTED_REG	0x094
#define XDPRX_VRD_BWSET_REG		0x09c
#define XDPRX_LANE_CNT_REG		0x0a0
#define XDPRX_EFRAME_CAP_MASK		BIT(7)
#define XDPRX_LNCNT_TPS3_MASK		BIT(6)

#define XDPRX_TP_SET_REG		0x0a4
#define XDPRX_AUX_RDINT_SHIFT		8
#define XDPRX_AUX_RDINT_16MS		4
#define XDPRX_AUX_READINTRVL_MASK	BIT(15)

#define XDPRX_CTRL_DPCD_REG		0x0b8
#define XDPRX_MST_CAP_REG		0x0d0
#define XDPRX_MST_CAP_ENABLE_MASK	BIT(0)
#define XDPRX_MST_CAP_SOFT_VCP_MASK	BIT(1)
#define XDPRX_MST_CAP_OVER_ACT_MASK	BIT(2)
#define XDPRX_MST_CAP_VCP_UPDATE_MASK	BIT(4)
#define XDPRX_MST_CAP_VCP_CLEAR_MASK	BIT(8)
#define XDPRX_SINK_COUNT_REG		0x0d4

#define XDPRX_PHY_REG			0x200
#define XDPRX_PHY_GTPLLRST_MASK		BIT(0)
#define XDPRX_PHY_GTRXRST_MASK		BIT(1)
#define XDPRX_PHYRST_TRITER_MASK	BIT(23)
#define XDPRX_PHYRST_RATECHANGE_MASK	BIT(24)
#define XDPRX_PHYRST_TP1START_MASK	BIT(25)
#define XDPRX_PHYRST_ENBL_MASK		0x0	/* PHY reset disabled */
#define XDPRX_PHY_INIT_MASK		GENMASK(29, 27)

#define XDPRX_PHYSTATUS_REG			0x208
#define XDPRX_PHYSTATUS_ALL_LANES_GOOD_MASK	GENMASK(6, 0)
#define XDPRX_PHYSTATUS_READ_COUNT	100

#define XDPRX_MINVOLT_SWING_REG		0x214
#define XDPRX_VS_PE_SHIFT		12
#define XDPRX_VS_SWEEP_CNTSHIFT		4
#define XDPRX_VS_CROPT_SHIFT		2
#define XDPRX_VS_CROPT_INC4CNT		1
#define XDPRX_MIN_VS_MASK		(1 | (XDPRX_VS_CROPT_INC4CNT << \
					 XDPRX_VS_CROPT_SHIFT) | \
					 (4 << XDPRX_VS_SWEEP_CNTSHIFT) | \
					 (1 << XDPRX_VS_PE_SHIFT))

#define XDPRX_CDRCTRL_CFG_REG		0x21c
/* default CDR tDLOCK calibration value */
#define XDPRX_CDRCTRL_TDLOCK_VAL	0x1388
#define XDPRX_CDRCTRL_TDLOCK_MASK	GENMASK(19, 0)
#define XDPRX_CDRCTRL_DIS_TIMEOUT	BIT(30)

#define XDPRX_BSIDLE_TIME_REG		0x220
#define XDPRX_BSIDLE_TMOUT_VAL		0x047868c0

#define XDPRX_AUDIO_CONTROL		0x300
#define XDPRX_AUDIO_EN_MASK		BIT(0)
#define XDPRX_AUDIO_INFO_DATA		0x304
#define XDPRX_AUDIO_MAUD		0x324
#define XDPRX_AUDIO_NAUD		0x328
#define XDPRX_AUDIO_STATUS		0x32c

#define XDPRX_LINK_BW_REG		0x400
#define XDPRX_LANE_COUNT_REG		0x404
#define XDPRX_DPCD_TRAINING_PATTERN_SET	0x40c
#define XDPRX_DPCD_SET_POWER_STATE	0x438
#define XDPRX_POWERNORMAL_STATE		1
#define XDPRX_DPCD_LANE01_STATUS	0x43c
#define XDPRX_LANE01_PEVS_MASK		GENMASK(15, 8)
#define XDPRX_DPC_LINK_QUAL_CONFIG	0x454
#define XDPRX_DPCD_LINK_QUAL_PRBS_MASK	GENMASK(1, 0)
#define XDPRX_LINK_QUAL_PRBS_MODE_MASK	GENMASK(2, 0)
#define XDPRX_MSA_HRES_REG		0x500
#define XDPRX_MSA_HSPOL_REG		0x504
#define XDPRX_MSA_HSPOL_MASK		BIT(0)
#define XDPRX_MSA_HSWIDTH_REG		0x508
#define XDPRX_MSA_HSTART_REG		0x50c
#define XDPRX_MSA_VHEIGHT_REG		0x514
#define XDPRX_MSA_HTOTAL_REG		0x510
#define XDPRX_MSA_VSPOL_REG		0x518
#define XDPRX_MSA_VSPOL_MASK		BIT(0)
#define XDPRX_MSA_VSWIDTH_REG		0x51c
#define XDPRX_MSA_VSTART_REG		0x520
#define XDPRX_MSA_VTOTAL_REG		0x524
#define XDPRX_MSA_MISC0_REG		0x528
#define XDPRX_MSA_FMT_MASK		GENMASK(2, 1)
#define XDPRX_MSA_BPC_MASK		GENMASK(7, 5)
#define XDPRX_COLOR_DEPTH_SHIFT		5
#define XDPRX_COLOR_FMT_SHIFT		1

#define XDPRX_MSA_MISC1_REG		0x52c
#define XDPRX_INTERLACE_MASK		BIT(0)
#define XDPRX_DPCD_MSA_TIMING_IGNORE_MASK	BIT(6)
#define XDPRX_MSA_MVID_REG		0x530
#define XDPRX_MSA_NVID_REG		0x534
#define XDPRX_INTR_ERRORCNT_MASK	BIT(28)
#define XDPRX_INTR_LANESET_MASK		BIT(30)
#define XDPRX_SDP_PAYLOAD_STREAM1	0x644
#define XDPRX_VSC_SDP_FMT_MASK		GENMASK(7, 4)
#define XDPRX_VSC_SDP_BPC_MASK		GENMASK(11, 8)
#define XDPRX_EXT_VRD_BWSET_REG		0x7f0

/* table 2-96 DP Spec 1.4 */
#define XDPRX_MSA_BPC_6			0x00
#define XDPRX_MSA_BPC_8			0x01
#define XDPRX_MSA_BPC_10		0x02
#define XDPRX_MSA_BPC_12		0x03
#define XDPRX_MSA_BPC_16		0x04

#define XDPRX_COLOR_FORMAT_RGB		0x0
#define XDPRX_COLOR_FORMAT_422		0x1
#define XDPRX_COLOR_FORMAT_444		0x2
#define XDPRX_COLOR_FORMAT_420		0x3

#define XDPRX_MAX_LANE_COUNT		4

#define XDPRX_EDID_NUM_BLOCKS		3
#define XDPRX_EDID_BLOCK_SIZE		128
#define XDPRX_EDID_LENGTH		(XDPRX_EDID_BLOCK_SIZE * \
					 XDPRX_EDID_NUM_BLOCKS * 4)
/*
 * IRQ_HPD pulse for upstream device is 5ms as per
 * the VESA standard
 */
#define XDPRX_HPD_PULSE_5000		5000
/*
 * low going IRQ_HPD generated for upstream device
 * as per the VESA standard
 */
#define XDPRX_HPD_PULSE_750		750

/* GtCtrl Registers */
#define XDPRX_GTCTL_REG			0x4c
#define XDPRX_GTCTL_EN			BIT(0)
#define XDPRX_GTCTL_VSWING_MASK		GENMASK(12, 8)
#define XDPRX_GTCTL_VSWING_INIT_VAL	0x05
#define XDPRX_GTCTL_LINE_RATE_MASK	GENMASK(2, 1)
#define XDPRX_GTCTL_LINE_RATE_810G	3
#define XDPRX_GTCTL_LINE_RATE_540G	2
#define XDPRX_GTCTL_LINE_RATE_270G	1
#define XDPRX_GTCTL_LINE_RATE_162G	0

#define XDPRX_LINK_BW_1_62G	1620
#define XDPRX_LINK_BW_2_7G		2700
#define XDPRX_LINK_BW_5_4G		5400    /* 1.2 */
#define XDPRX_LINK_BW_8_1G		8100    /* 1.4 */

#define XDPRXSS_MMCM_OFFSET		0x5000

/* Clock Wizard registers */
#define XDPRX_MMCM_SWRST_OFFSET		0x00000000
#define XDPRX_MMCM_SWRST_VAL		0xa
#define XDPRX_MMCM_STATUS_OFFSET	0x00000004
#define XDPRX_MMCM_ISR_OFFSET		0x0000000c
#define XDPRX_MMCM_IER_OFFSET		0x00000010
#define XDPRX_MMCM_RECONFIG_OFFSET	0x00000014
#define XDPRX_MMCM_REG1_OFFSET		0x00000330
#define XDPRX_MMCM_REG2_OFFSET		0x00000334
#define XDPRX_MMCM_REG3_OFFSET		0x00000338
#define XDPRX_MMCM_REG4_OFFSET		0x0000033c
#define XDPRX_MMCM_REG12_OFFSET		0x00000380
#define XDPRX_MMCM_REG13_OFFSET		0x00000384
#define XDPRX_MMCM_REG11_OFFSET		0x00000378
#define XDPRX_MMCM_REG11_VAL		0x2e
#define XDPRX_MMCM_REG14_OFFSET		0x00000398
#define XDPRX_MMCM_REG14_VAL		0xe80
#define XDPRX_MMCM_REG15_OFFSET		0x0000039c
#define XDPRX_MMCM_REG15_VAL		0x4271
#define XDPRX_MMCM_REG16_OFFSET		0x000003a0
#define XDPRX_MMCM_REG16_VAL		0x43e9
#define XDPRX_MMCM_REG17_OFFSET		0x000003a8
#define XDPRX_MMCM_REG17_VAL		0x1c
#define XDPRX_MMCM_REG19_OFFSET		0x000003cc
#define XDPRX_MMCM_REG25_OFFSET		0x000003f0
#define XDPRX_MMCM_REG26_OFFSET		0x000003fc
#define XDPRX_MMCM_REG26_VAL		1

#define XDPRX_MMCM_LOCK			BIT(0)
#define XDPRX_MMCM_REG3_PREDIV2		BIT(11)
#define XDPRX_MMCM_REG3_USED		BIT(12)
#define XDPRX_MMCM_REG3_MX		BIT(9)
#define XDPRX_MMCM_REG1_PREDIV2		BIT(12)
#define XDPRX_MMCM_REG1_EN		BIT(9)
#define XDPRX_MMCM_REG1_MX		BIT(10)
#define XDPRX_MMCM_RECONFIG_LOAD	BIT(0)
#define XDPRX_MMCM_RECONFIG_SADDR	BIT(1)
#define XDPRX_MMCM_REG1_EDGE_MASK	BIT(8)

#define XDPRX_MMCM_CLKOUT0_PREDIV2_SHIFT	11
#define XDPRX_MMCM_CLKOUT0_MX_SHIFT		9
#define XDPRX_MMCM_CLKOUT0_P5EN_SHIFT		13
#define XDPRX_MMCM_CLKOUT0_P5FEDGE_SHIFT	15
#define XDPRX_MMCM_REG12_EDGE_SHIFT		10

#define XDPRX_MMCM_M_VAL_405		28
#define XDPRX_MMCM_M_VAL_270		44
#define XDPRX_MMCM_M_VAL_135		88
#define XDPRX_MMCM_M_VAL_81		148
#define XDPRX_MMCM_D_VAL		5
#define XDPRX_MMCM_M_O_VAL_RATIO	4
#define XDPRX_MMCM_STATUS_RETRY		10000

#define XDPRX_MMCM_O_VAL_FEDGE_DIVIDER	2
#define XDPRX_MMCM_O_VAL_HIGHTIME_DIVIDER	4
#define XDPRX_MMCM_O_VAL_EDGE_DIVIDER		4
#define XDPRX_MMCM_D_VAL_EDGE_DIVIDER		2
#define XDPRX_MMCM_D_VAL_HIGHTIME_DIVIDER	2
#define XDPRX_MMCM_M_VAL_EDGE_DIVIDER		2
#define XDPRX_MMCM_M_VAL_HIGHTIME_DIVIDER	2
#define XDPRX_MMCM_MDO_VAL_HIGHTIME_SHIFT	8

#define XDPRX_HDCP1X_REG_OFFSET			0x4000
#define XDPRX_BYTES_PER_RDWR				4
#define XDPRX_ALIGN_FOR_RDWR				0x3

#define XDPRX_DPCD_HDCP1X_PORT_REG_LENGTH	0x100
#define XDPRX_DPCD_HDCP1X_PORT_OFST		0x900
#define XDPRX_DPCD_HDCP1X_PORT_KSVFIFO		0x02c

#define HDCP1X_KEYMGMT_REG_VERSION		0x0000
#define HDCP1X_KEYMGMT_REG_TYPE			0x0004
#define HDCP1X_KEYMGMT_REG_SCRATCH		0x0008
#define HDCP1X_KEYMGMT_REG_CTRL			0x000c
#define HDCP1X_KEYMGMT_REG_STATUS		0x0010
#define HDCP1X_KEYMGMT_REG_TBL_CTRL		0x0020
#define HDCP1X_KEYMGMT_REG_TBL_STATUS		0x0024
#define HDCP1X_KEYMGMT_REG_TBL_ADDR		0x0028
#define HDCP1X_KEYMGMT_REG_TBL_DAT_H		0x002c
#define HDCP1X_KEYMGMT_REG_TBL_DAT_L		0x0030
#define HDCP1X_KEYMGMT_REG_MAX			0x0040

#define HDCP1X_KEYMGMT_REG_CTRL_RST_MASK	BIT(31)
#define HDCP1X_KEYMGMT_REG_CTRL_DISABLE_MASK	GENMASK(31, 1)
#define HDCP1X_KEYMGMT_REG_CTRL_ENABLE_MASK	BIT(0)
#define HDCP1X_KEYMGMT_REG_TBL_STATUS_RETRY	0x400
#define HDCP1X_KEYMGMT_TBLID_0			0
#define HDCP1X_KEYS_SIZE			336
#define HDCP2X_LC128_SIZE			16
#define HDCP2X_PRIVATE_SIZE			996
#define HDCP1X_KEYMGMT_REG_TBL_CTRL_WR_MASK	BIT(0)
#define HDCP1X_KEYMGMT_REG_TBL_CTRL_RD_MASK	BIT(1)
#define HDCP1X_KEYMGMT_REG_TBL_CTRL_EN_MASK	BIT(31)
#define HDCP1X_KEYMGMT_REG_TBL_STATUS_DONE_MASK	BIT(0)
#define HDCP1X_KEYMGMT_MAX_TBLS			8
#define HDCP1X_KEYMGMT_MAX_ROWS_PER_TBL		41
#define XDPRX_LINK_ENABLE_DELAY_MS		20

#define XDPRX_MST_ALLOC_VCP_ID_MASK	GENMASK(5, 0)
#define XDPRX_MST_ALLOC_START_TS_MASK	GENMASK(13, 8)
#define XDPRX_MST_ALLOC_COUNT_TS_MASK	GENMASK(21, 16)

/* MST VC payload and sideband message register windows */
#define XDPRX_VC_PAYLOAD_TABLE		0x800
#define XDPRX_DOWN_REQ			0xa00
#define XDPRX_DOWN_REP			0xb00

/* Per-stream video-valid interrupt masks (streams 1-4, relative to INTR_MASK_1) */
#define XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_MASK(stream) \
	(((stream) >= 1 && (stream) <= 4) ? (BIT(5) << (((stream) - 1) * 6)) : 0)
#define XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_ALT_MASK(stream) \
	(((stream) >= 1 && (stream) <= 4) ? (BIT(3) << (((stream) - 1) * 6)) : 0)
#define XDPRX_INTR_MASK_1_VALID_VIDEO_ALL \
	(XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_MASK(2) | \
	 XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_MASK(3) | \
	 XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_MASK(4) | \
	 XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_ALT_MASK(2) | \
	 XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_ALT_MASK(3) | \
	 XDPRX_INTERRUPT_MASK_1_VIDEO_STREAM_ALT_MASK(4))

#endif /* __XILINX_DPRXSS_HW_H__ */
