# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Radio over Ethernet Framer driver
#
obj-$(XROE_TRAFFIC_GEN)	:= xroe_traffic_gen.o

framer-objs := 	xroe-traffic-gen.o \
		xroe-traffic-gen-sysfs.o \
