
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.1 EDK_K_SP1.1
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/


/* Definitions for peripheral PLB_BRAM_IF_CNTLR_0 */
#define XPAR_PLB_BRAM_IF_CNTLR_0_BASEADDR 0xFFFF0000
#define XPAR_PLB_BRAM_IF_CNTLR_0_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PLB_BRAM_IF_CNTLR_1 */
#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0xEEE00000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0xEEE01FFF


/******************************************************************/

/* Definitions for driver UARTNS550 */
#define XPAR_XUARTNS550_NUM_INSTANCES 1
#define XPAR_XUARTNS550_CLOCK_HZ 20000000

/* Definitions for peripheral RS232_UART_0 */
#define XPAR_RS232_UART_0_DEVICE_ID 0
#define XPAR_RS232_UART_0_BASEADDR 0xD0000000
#define XPAR_RS232_UART_0_HIGHADDR 0xD0001FFF


/******************************************************************/


/* Canonical definitions for peripheral RS232_UART_0 */
#define XPAR_UARTNS550_0_CLOCK_FREQ_HZ 20000000
#define XPAR_UARTNS550_0_DEVICE_ID XPAR_RS232_UART_0_DEVICE_ID
#define XPAR_UARTNS550_0_BASEADDR 0xD0000000
#define XPAR_UARTNS550_0_HIGHADDR 0xD0001FFF
#define XPAR_UARTNS550_0_SIO_CHAN -1


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 8
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral OPB_INTC_0 */
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_BASEADDR 0xD0020200
#define XPAR_OPB_INTC_0_HIGHADDR 0xD002021F
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x00000000


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0xD0020200
#define XPAR_INTC_SINGLE_HIGHADDR 0xD002021F
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_RS232_UART_0_IP2INTC_IRPT_MASK 0X000001
#define XPAR_OPB_INTC_0_RS232_UART_0_IP2INTC_IRPT_INTR 0
#define XPAR_LEDS_8BIT_IP2INTC_IRPT_MASK 0X000002
#define XPAR_OPB_INTC_0_LEDS_8BIT_IP2INTC_IRPT_INTR 1
#define XPAR_SYSACE_COMPACTFLASH_SYSACE_IRQ_MASK 0X000004
#define XPAR_OPB_INTC_0_SYSACE_COMPACTFLASH_SYSACE_IRQ_INTR 2
#define XPAR_SYSTEM_PHY_MII_INT_N_MASK 0X000008
#define XPAR_OPB_INTC_0_SYSTEM_PHY_MII_INT_N_INTR 3
#define XPAR_LL_TEMAC_0_TEMACINTC0_IRPT_MASK 0X000010
#define XPAR_OPB_INTC_0_LL_TEMAC_0_TEMACINTC0_IRPT_INTR 4
#define XPAR_PPC440_VIRTEX5_0_DMA0RXIRQ_MASK 0X000020
#define XPAR_OPB_INTC_0_PPC440_VIRTEX5_0_DMA0RXIRQ_INTR 5
#define XPAR_PPC440_VIRTEX5_0_DMA0TXIRQ_MASK 0X000040
#define XPAR_OPB_INTC_0_PPC440_VIRTEX5_0_DMA0TXIRQ_INTR 6
#define XPAR_IIC_BUS_IIC2INTC_IRPT_MASK 0X000080
#define XPAR_OPB_INTC_0_IIC_BUS_IIC2INTC_IRPT_INTR 7

/******************************************************************/


/* Canonical definitions for peripheral OPB_INTC_0 */
#define XPAR_INTC_0_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0xD0020200
#define XPAR_INTC_0_HIGHADDR 0xD002021F
#define XPAR_INTC_0_KIND_OF_INTR 0x00000000

#define XPAR_INTC_0_UARTNS550_0_VEC_ID XPAR_OPB_INTC_0_RS232_UART_0_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_GPIO_0_VEC_ID XPAR_OPB_INTC_0_LEDS_8BIT_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SYSACE_0_VEC_ID XPAR_OPB_INTC_0_SYSACE_COMPACTFLASH_SYSACE_IRQ_INTR
#define XPAR_INTC_0_LLTEMAC_0_VEC_ID XPAR_OPB_INTC_0_LL_TEMAC_0_TEMACINTC0_IRPT_INTR
#define XPAR_INTC_0_CPU_PPC440_0_DMA0RXIRQ_VEC_ID XPAR_OPB_INTC_0_PPC440_VIRTEX5_0_DMA0RXIRQ_INTR
#define XPAR_INTC_0_CPU_PPC440_0_DMA0TXIRQ_VEC_ID XPAR_OPB_INTC_0_PPC440_VIRTEX5_0_DMA0TXIRQ_INTR
#define XPAR_INTC_0_IIC_0_VEC_ID XPAR_OPB_INTC_0_IIC_BUS_IIC2INTC_IRPT_INTR

/******************************************************************/

#define XPAR_XSYSACE_MEM_WIDTH 16
/* Definitions for driver SYSACE */
#define XPAR_XSYSACE_NUM_INSTANCES 1

/* Definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_COMPACTFLASH_DEVICE_ID 0
#define XPAR_SYSACE_COMPACTFLASH_BASEADDR 0xD0030100
#define XPAR_SYSACE_COMPACTFLASH_HIGHADDR 0xD003017F
#define XPAR_SYSACE_COMPACTFLASH_MEM_WIDTH 16


/******************************************************************/


/* Canonical definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_0_DEVICE_ID XPAR_SYSACE_COMPACTFLASH_DEVICE_ID
#define XPAR_SYSACE_0_BASEADDR 0xD0030100
#define XPAR_SYSACE_0_HIGHADDR 0xD003017F
#define XPAR_SYSACE_0_MEM_WIDTH 16


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral IIC_BUS */
#define XPAR_IIC_BUS_DEVICE_ID 0
#define XPAR_IIC_BUS_BASEADDR 0xD0020000
#define XPAR_IIC_BUS_HIGHADDR 0xD00201FF
#define XPAR_IIC_BUS_TEN_BIT_ADR 0
#define XPAR_IIC_BUS_GPO_WIDTH 1


/******************************************************************/


/* Canonical definitions for peripheral IIC_BUS */
#define XPAR_IIC_0_DEVICE_ID XPAR_IIC_BUS_DEVICE_ID
#define XPAR_IIC_0_BASEADDR 0xD0020000
#define XPAR_IIC_0_HIGHADDR 0xD00201FF
#define XPAR_IIC_0_TEN_BIT_ADR 0
#define XPAR_IIC_0_GPO_WIDTH 1


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 1

/* Definitions for peripheral LEDS_8BIT */
#define XPAR_LEDS_8BIT_BASEADDR 0xD0010200
#define XPAR_LEDS_8BIT_HIGHADDR 0xD00103FF
#define XPAR_LEDS_8BIT_DEVICE_ID 0
#define XPAR_LEDS_8BIT_INTERRUPT_PRESENT 1
#define XPAR_LEDS_8BIT_IS_DUAL 0


/******************************************************************/

/* Definitions for driver LLTEMAC */
#define XPAR_XLLTEMAC_NUM_INSTANCES 1

/* Definitions for peripheral LL_TEMAC_0 Channel 0 */
#define XPAR_LL_TEMAC_0_CHAN_0_DEVICE_ID 0
#define XPAR_LL_TEMAC_0_CHAN_0_BASEADDR 0x91200000
#define XPAR_LL_TEMAC_0_CHAN_0_TXCSUM 0
#define XPAR_LL_TEMAC_0_CHAN_0_RXCSUM 0
#define XPAR_LL_TEMAC_0_CHAN_0_PHY_TYPE 1

/* Canonical definitions for peripheral LL_TEMAC_0 Channel 0 */
#define XPAR_LLTEMAC_0_DEVICE_ID 0
#define XPAR_LLTEMAC_0_BASEADDR 0x91200000
#define XPAR_LLTEMAC_0_TXCSUM 0
#define XPAR_LLTEMAC_0_RXCSUM 0
#define XPAR_LLTEMAC_0_PHY_TYPE 1
#define XPAR_LLTEMAC_0_INTR 4


/* LocalLink TYPE Enumerations */
#define XPAR_LL_FIFO    1
#define XPAR_LL_DMA     2


/* Canonical LocalLink parameters for LL_TEMAC_0 */
#define XPAR_LLTEMAC_0_LLINK_CONNECTED_TYPE XPAR_LL_DMA
#define XPAR_LLTEMAC_0_LLINK_CONNECTED_BASEADDR 0x80
#define XPAR_LLTEMAC_0_LLINK_CONNECTED_FIFO_INTR 0xFF
#define XPAR_LLTEMAC_0_LLINK_CONNECTED_DMATX_INTR 6
#define XPAR_LLTEMAC_0_LLINK_CONNECTED_DMARX_INTR 5


/******************************************************************/


/* Definitions for peripheral PPC440MC_DDR2_0 */
#define XPAR_PPC440MC_DDR2_0_MEM_BASEADDR 0x00000000
#define XPAR_PPC440MC_DDR2_0_MEM_HIGHADDR 0x1FFFFFFF


/******************************************************************/

#define XPAR_CPU_PPC440_CORE_CLOCK_FREQ_HZ 400000000
#define XPAR_CPU_PPC440_IDCR_BASEADDR 0x00000000
#define XPAR_XLLDMA_USE_DCR
/******************************************************************/
#define XPAR_CORE_CLOCK_FREQ_HZ XPAR_CPU_PPC440_CORE_CLOCK_FREQ_HZ

/******************************************************************/

#define XPAR_PCI_0_CLOCK_FREQ_HZ    0

#define XPAR_PLB_CLOCK_FREQ_HZ 100000000
#define XPAR_DDR_0_SIZE 0x10000000

/******************************************************************/

#define XPAR_PERSISTENT_0_IIC_0_BASEADDR 0
#define XPAR_PERSISTENT_0_IIC_0_HIGHADDR 1024
#define XPAR_PERSISTENT_0_IIC_0_EEPROMADDR 0xA0

