
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 8.2.02 EDK_Im_Sp2.4
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver parameters
*
*******************************************************************/

/* Definitions for driver PLBARB */
#define XPAR_XPLBARB_NUM_INSTANCES 1

/* Definitions for peripheral PLB */
#define XPAR_PLB_BASEADDR 0x00000000
#define XPAR_PLB_HIGHADDR 0x00000000
#define XPAR_PLB_DEVICE_ID 0
#define XPAR_PLB_PLB_NUM_MASTERS 3


/******************************************************************/

/* Definitions for driver OPBARB */
#define XPAR_XOPBARB_NUM_INSTANCES 1

/* Definitions for peripheral OPB */
#define XPAR_OPB_BASEADDR 0xFFFFFFFF
#define XPAR_OPB_HIGHADDR 0x00000000
#define XPAR_OPB_DEVICE_ID 0
#define XPAR_OPB_NUM_MASTERS 1

/******************************************************************/


/* Definitions for peripheral OPB_SOCKET_0 */
#define XPAR_OPB_SOCKET_0_BASEADDR 0x40000000
#define XPAR_OPB_SOCKET_0_HIGHADDR 0x7FFFFFFF
#define XPAR_OPB_SOCKET_0_DCR_BASEADDR 0x40700300
#define XPAR_OPB_SOCKET_0_DCR_HIGHADDR 0x40700307

/******************************************************************/

/* Definitions for driver UARTNS550 */
#define XPAR_XUARTNS550_NUM_INSTANCES 2
#define XPAR_XUARTNS550_CLOCK_HZ 100000000

/* Definitions for peripheral RS232_UART_1 */
#define XPAR_RS232_UART_1_BASEADDR 0x40400000
#define XPAR_RS232_UART_1_HIGHADDR 0x4040FFFF
#define XPAR_RS232_UART_1_DEVICE_ID 0


/* Definitions for peripheral RS232_UART_2 */
#define XPAR_RS232_UART_2_BASEADDR 0x40420000
#define XPAR_RS232_UART_2_HIGHADDR 0x4042FFFF
#define XPAR_RS232_UART_2_DEVICE_ID 1


/******************************************************************/

/* Definitions for driver SPI */
#define XPAR_XSPI_NUM_INSTANCES 1

/* Definitions for peripheral SPI_EEPROM */
#define XPAR_SPI_EEPROM_BASEADDR 0x40A00000
#define XPAR_SPI_EEPROM_HIGHADDR 0x40A0FFFF
#define XPAR_SPI_EEPROM_DEVICE_ID 0
#define XPAR_SPI_EEPROM_FIFO_EXIST 1
#define XPAR_SPI_EEPROM_SPI_SLAVE_ONLY 0
#define XPAR_SPI_EEPROM_NUM_SS_BITS 1


/******************************************************************/

#define XPAR_XSYSACE_MEM_WIDTH 16
/* Definitions for driver SYSACE */
#define XPAR_XSYSACE_NUM_INSTANCES 1

/* Definitions for peripheral SYSACE_COMPACTFLASH */
#define XPAR_SYSACE_COMPACTFLASH_BASEADDR 0x41800000
#define XPAR_SYSACE_COMPACTFLASH_HIGHADDR 0x4180FFFF
#define XPAR_SYSACE_COMPACTFLASH_DEVICE_ID 0
#define XPAR_SYSACE_COMPACTFLASH_MEM_WIDTH 16


/******************************************************************/

/* Definitions for driver IIC */
#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral IIC_BUS */
#define XPAR_IIC_BUS_BASEADDR 0x40800000
#define XPAR_IIC_BUS_HIGHADDR 0x4080FFFF
#define XPAR_IIC_BUS_DEVICE_ID 0
#define XPAR_IIC_BUS_TEN_BIT_ADR 0
#define XPAR_IIC_BUS_GPO_WIDTH 1


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 6
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_USE_DCR 0
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral OPB_INTC_0 */
#define XPAR_OPB_INTC_0_BASEADDR 0x41200000
#define XPAR_OPB_INTC_0_HIGHADDR 0x4120FFFF
#define XPAR_OPB_INTC_0_DEVICE_ID 0
#define XPAR_OPB_INTC_0_KIND_OF_INTR 0x00000000


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID
#define XPAR_ETHERNET_MAC_IP2INTC_IRPT_MASK 0X000001
#define XPAR_OPB_INTC_0_ETHERNET_MAC_IP2INTC_IRPT_INTR 0
#define XPAR_IIC_BUS_IP2INTC_IRPT_MASK 0X000002
#define XPAR_OPB_INTC_0_IIC_BUS_IP2INTC_IRPT_INTR 1
#define XPAR_SYSACE_COMPACTFLASH_SYSACE_IRQ_MASK 0X000004
#define XPAR_OPB_INTC_0_SYSACE_COMPACTFLASH_SYSACE_IRQ_INTR 2
#define XPAR_SPI_EEPROM_IP2INTC_IRPT_MASK 0X000008
#define XPAR_OPB_INTC_0_SPI_EEPROM_IP2INTC_IRPT_INTR 3
#define XPAR_RS232_UART_2_IP2INTC_IRPT_MASK 0X000010
#define XPAR_OPB_INTC_0_RS232_UART_2_IP2INTC_IRPT_INTR 4
#define XPAR_RS232_UART_1_IP2INTC_IRPT_MASK 0X000020
#define XPAR_OPB_INTC_0_RS232_UART_1_IP2INTC_IRPT_INTR 5

/******************************************************************/

/* Definitions for driver HWICAP */
#define XPAR_XHWICAP_NUM_INSTANCES 1
 
/* Definitions for peripheral OPB_HWICAP_0 */
#define XPAR_OPB_HWICAP_0_BASEADDR 0x41300000
#define XPAR_OPB_HWICAP_0_HIGHADDR 0x4130FFFF
#define XPAR_OPB_HWICAP_0_DEVICE_ID 0

/******************************************************************/

/* Definitions for driver DDR */
#define XPAR_XDDR_NUM_INSTANCES 1

/* Definitions for peripheral DDR_SDRAM_32MX64 */
#define XPAR_DDR_SDRAM_32MX64_ECC_BASEADDR 0xFFFFFFFF
#define XPAR_DDR_SDRAM_32MX64_ECC_HIGHADDR 0x00000000
#define XPAR_DDR_SDRAM_32MX64_DEVICE_ID 0
#define XPAR_DDR_SDRAM_32MX64_INCLUDE_ECC_INTR 0


/******************************************************************/

/* Definitions for peripheral DDR_SDRAM_32MX64 */
#define XPAR_DDR_SDRAM_32MX64_MEM0_BASEADDR 0x00000000
#define XPAR_DDR_SDRAM_32MX64_MEM0_HIGHADDR 0x03FFFFFF

/******************************************************************/

/* Definitions for driver EMAC */
#define XPAR_XEMAC_NUM_INSTANCES 1

/* Definitions for peripheral ETHERNET_MAC */
#define XPAR_ETHERNET_MAC_BASEADDR 0x80400000
#define XPAR_ETHERNET_MAC_HIGHADDR 0x8040FFFF
#define XPAR_ETHERNET_MAC_DEVICE_ID 0
#define XPAR_ETHERNET_MAC_ERR_COUNT_EXIST 1
#define XPAR_ETHERNET_MAC_DMA_PRESENT 1
#define XPAR_ETHERNET_MAC_MII_EXIST 1


/******************************************************************/


/* Definitions for peripheral PLB_BRAM_IF_CNTLR_1 */
#define XPAR_PLB_BRAM_IF_CNTLR_1_BASEADDR 0xfffff000
#define XPAR_PLB_BRAM_IF_CNTLR_1_HIGHADDR 0xffffffff


/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 300000000

/******************************************************************/


/******************************************************************/

/* Cannonical Constant Names */

/******************************************************************/

#define XPAR_UARTNS550_0_BASEADDR (XPAR_RS232_UART_1_BASEADDR+0x1000)
#define XPAR_UARTNS550_0_HIGHADDR XPAR_RS232_UART_1_HIGHADDR
#define XPAR_UARTNS550_0_CLOCK_FREQ_HZ XPAR_XUARTNS550_CLOCK_HZ
#define XPAR_UARTNS550_0_DEVICE_ID XPAR_RS232_UART_1_DEVICE_ID
#define XPAR_UARTNS550_1_BASEADDR (XPAR_RS232_UART_2_BASEADDR+0x1000)
#define XPAR_UARTNS550_1_HIGHADDR XPAR_RS232_UART_2_HIGHADDR
#define XPAR_UARTNS550_1_CLOCK_FREQ_HZ XPAR_XUARTNS550_CLOCK_HZ
#define XPAR_UARTNS550_1_DEVICE_ID XPAR_RS232_UART_2_DEVICE_ID

/******************************************************************/

#define XPAR_SPI_0_BASEADDR XPAR_SPI_EEPROM_BASEADDR
#define XPAR_SPI_0_HIGHADDR XPAR_SPI_EEPROM_HIGHADDR
#define XPAR_SPI_0_FIFO_EXIST XPAR_SPI_EEPROM_FIFO_EXIST
#define XPAR_SPI_0_SPI_SLAVE_ONLY XPAR_SPI_EEPROM_SPI_SLAVE_ONLY
#define XPAR_SPI_0_NUM_SS_BITS XPAR_SPI_EEPROM_NUM_SS_BITS
#define XPAR_SPI_0_DEVICE_ID XPAR_SPI_EEPROM_DEVICE_ID

/******************************************************************/

#define XPAR_SYSACE_0_BASEADDR XPAR_SYSACE_COMPACTFLASH_BASEADDR
#define XPAR_SYSACE_0_HIGHADDR XPAR_SYSACE_COMPACTFLASH_HIGHADDR
#define XPAR_SYSACE_0_DEVICE_ID XPAR_SYSACE_COMPACTFLASH_DEVICE_ID

/******************************************************************/

#define XPAR_IIC_0_BASEADDR XPAR_IIC_BUS_BASEADDR
#define XPAR_IIC_0_HIGHADDR XPAR_IIC_BUS_HIGHADDR
#define XPAR_IIC_0_TEN_BIT_ADR XPAR_IIC_BUS_TEN_BIT_ADR
#define XPAR_IIC_0_DEVICE_ID XPAR_IIC_BUS_DEVICE_ID

/******************************************************************/

#define XPAR_EMAC_0_BASEADDR XPAR_ETHERNET_MAC_BASEADDR
#define XPAR_EMAC_0_HIGHADDR XPAR_ETHERNET_MAC_HIGHADDR
#define XPAR_EMAC_0_DMA_PRESENT XPAR_ETHERNET_MAC_DMA_PRESENT
#define XPAR_EMAC_0_MII_EXIST XPAR_ETHERNET_MAC_MII_EXIST
#define XPAR_EMAC_0_ERR_COUNT_EXIST XPAR_ETHERNET_MAC_ERR_COUNT_EXIST
#define XPAR_EMAC_0_DEVICE_ID XPAR_ETHERNET_MAC_DEVICE_ID

/******************************************************************/

#define XPAR_HWICAP_0_BASEADDR XPAR_OPB_HWICAP_0_BASEADDR
#define XPAR_HWICAP_0_HIGHADDR XPAR_OPB_HWICAP_0_HIGHADDR
#define XPAR_HWICAP_0_DEVICE_ID XPAR_OPB_HWICAP_0_DEVICE_ID

/******************************************************************/

#define XPAR_INTC_0_BASEADDR XPAR_OPB_INTC_0_BASEADDR
#define XPAR_INTC_0_HIGHADDR XPAR_OPB_INTC_0_HIGHADDR
#define XPAR_INTC_0_KIND_OF_INTR XPAR_OPB_INTC_0_KIND_OF_INTR
#define XPAR_INTC_0_DEVICE_ID XPAR_OPB_INTC_0_DEVICE_ID

/******************************************************************/

#define XPAR_INTC_0_EMAC_0_VEC_ID XPAR_OPB_INTC_0_ETHERNET_MAC_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_IIC_0_VEC_ID XPAR_OPB_INTC_0_IIC_BUS_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_SYSACE_0_VEC_ID XPAR_OPB_INTC_0_SYSACE_COMPACTFLASH_SYSACE_IRQ_INTR
#define XPAR_INTC_0_SPI_0_VEC_ID XPAR_OPB_INTC_0_SPI_EEPROM_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_UARTNS550_1_VEC_ID XPAR_OPB_INTC_0_RS232_UART_2_IP2INTC_IRPT_INTR
#define XPAR_INTC_0_UARTNS550_0_VEC_ID XPAR_OPB_INTC_0_RS232_UART_1_IP2INTC_IRPT_INTR

/******************************************************************/

#define XPAR_PLB_CLOCK_FREQ_HZ 100000000
#define XPAR_CORE_CLOCK_FREQ_HZ XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ
#define XPAR_DDR_0_SIZE 64000000

/******************************************************************/

#define XPAR_PERSISTENT_0_IIC_0_BASEADDR 1024
#define XPAR_PERSISTENT_0_IIC_0_HIGHADDR 2047
#define XPAR_PERSISTENT_0_IIC_0_EEPROMADDR 0xA0

/******************************************************************/

#define XPAR_PCI_0_CLOCK_FREQ_HZ    0

/******************************************************************/

