obj-$(CONFIG_RPMSG)	+= virtio_rpmsg_bus.o
obj-$(CONFIG_RPMSG_SERVER_SAMPLE) += rpmsg_server_sample.o
obj-$(CONFIG_RPMSG_FREERTOS_STAT) += rpmsg_freertos_statistic.o
obj-$(CONFIG_RPMSG_OMX) += rpmsg_omx.o
obj-$(CONFIG_RPMSG)            += host/
