# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_XILINX_VCU)	+= xlnx_vcu_core.o xlnx_vcu_clk.o xlnx_vcu.o
obj-$(CONFIG_ZYNQMP_POWER)	+= zynqmp_power.o
obj-$(CONFIG_ZYNQMP_PM_DOMAINS) += zynqmp_pm_domains.o

obj-$(CONFIG_ARCH_ZYNQMP)	+= zynqmp/
