#TODO: Need to remove these flags and fix compilation warnings.
ccflags-y := -Wno-incompatible-pointer-types -Wno-packed-bitfield-compat

obj-m += xernic.o
obj-m += xernic_bw_test.o

xernic-objs := xmain.o xcm.o xqp.o xmr.o
