# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_PHY_XILINX_ZYNQMP)		+= phy-zynqmp.o
obj-$(CONFIG_PHY_XILINX_HDMIPHY)       += xilinx-hdmiphy.o
xilinx-hdmiphy-objs := xhdmiphy.o
xilinx-hdmiphy-objs += xhdmiphy_core.o
xilinx-hdmiphy-objs += xhdmiphy_modules.o
xilinx-hdmiphy-objs += xhdmiphy_gt_helper.o
xilinx-hdmiphy-objs += xhdmiphy_mmcm.o
